import type { L } from "@/lib/i18n";
import type { CaseStudy } from "./types";

/**
 * Case library.
 *
 * Client entries are anonymised engagement summaries that were published on
 * the previous fimmick.com case-studies page (captured 28 Sep 2026). Client
 * identities were not published there and are not added here. The previous
 * page showed headline outcome figures; they are deliberately NOT repeated
 * because their scope, dates, baselines and definitions are not documented in
 * the source record. Re-introduce a figure only with approved evidence.
 */
/** One provenance line for every anonymised client case (no period is recorded, so none is shown). */
const provenance: L = {
  en: "Anonymised client engagement. Described, not quantified until the client approves figures.",
  zh: "匿名客戶項目。在客戶批准公開數字前，只作描述，不作量化。",
};

type Draft = Omit<CaseStudy, "kind" | "publicationBasis" | "context"> & { context?: L };

const client = (d: Draft): CaseStudy => ({
  kind: "client-work",
  publicationBasis: provenance,
  context: d.context ?? { en: `${d.sector.en} · ${d.market.en}`, zh: `${d.sector.zh}·${d.market.zh}` },
  ...d,
});

export const cases: CaseStudy[] = [
  {
    slug: "fimmick-ai-native-operating-model",
    kind: "internal-application",
    title: { en: "Redesigning FIMMICK’s own delivery work before offering it to clients", zh: "先改造 FIMMICK 自身的工作方式，再提供給客戶" },
    sector: { en: "FIMMICK · internal operations", zh: "FIMMICK·內部營運" },
    market: { en: "Hong Kong", zh: "香港" },
    industries: [],
    services: ["ai-transformation", "workflow-automation", "business-intelligence"],
    products: ["creativemax", "social-listening", "customer-ops"],
    publicationBasis: { en: "FIMMICK’s own operating experience, described by the company.", zh: "由 FIMMICK 描述的自身營運經驗。" },
    period: { en: "2024 onwards (company timeline)", zh: "2024 年起（公司發展時間線）" },
    context: {
      en: "Founded in Hong Kong in 2008, FIMMICK spent years running campaigns, content, CRM, social and reporting work for brands. From 2024 the company began turning its own recurring delivery work into configured AI workflows.",
      zh: "FIMMICK 於 2008 年在香港成立，多年來為品牌處理宣傳、內容、CRM、社交及報告工作。由 2024 年起，公司開始把自身的經常性交付工作轉化為已配置的 AI 流程。",
    },
    problem: {
      en: "Research, content preparation, reporting and follow-up were repeated by hand for every client, and quality depended on who happened to do the work.",
      zh: "研究、內容準備、報告及跟進要為每位客戶人手重複處理，質素取決於由誰負責。",
    },
    scope: { en: ["Recurring research and listening briefs", "Content preparation and review", "Reporting commentary", "Enquiry and follow-up records"], zh: ["經常性研究及聆聽簡報", "內容準備及審閱", "報告評述", "查詢及跟進紀錄"] },
    workflowBefore: { en: ["Each team rebuilt briefs and reports from scratch", "Approvals happened in chat threads", "Learning stayed with individuals"], zh: ["各團隊每次由零開始整理簡報及報告", "批核在聊天記錄中進行", "經驗只留在個別同事身上"] },
    workflowAfter: { en: ["Defined workflows with approved inputs", "AI prepares drafts; named people review", "Records kept so the next round improves"], zh: ["以已確認輸入界定流程", "AI 準備草稿，由指定人員審閱", "保留紀錄，令下一輪有所改善"] },
    humanDecisions: { en: "Account leads and specialists approve every client-facing output. Commercial and creative judgement stays with people.", zh: "所有面向客戶的輸出均由客戶主管及專家批准；商業及創意判斷仍由人負責。" },
    dataFoundation: { en: "Internal templates, approved client briefs and brand facts, reporting exports.", zh: "內部範本、已確認的客戶簡報及品牌資料、報告匯出檔。" },
    outcome: { en: "The practical experience behind FIMMICK AIP and the transformation method: what to automate, where people must decide, and what records make work reusable.", zh: "成為 FIMMICK AIP 及轉型方法背後的實戰經驗：哪些工作應自動化、哪些地方必須由人決定，以及哪些記錄能令工作得以重用。" },
    limitations: { en: "Internal experience, not a client result. Staffing and productivity figures are not published here.", zh: "此為內部經驗，並非客戶成果；此處不公開人手及生產力數字。" },
    reusable: { en: "Workflow patterns now offered through AIP products and transformation services.", zh: "相關流程模式現已透過 AIP 產品及轉型服務提供。" },
  },
  client({
    slug: "omni-channel-retail-intelligence", legacyId: 1,
    title: { en: "Omni-channel retail intelligence", zh: "全渠道零售數據洞察" },
    sector: { en: "Retail", zh: "零售" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["retail-ecommerce"], services: ["data-hub", "business-intelligence"], products: ["social-listening"],
    problem: { en: "A multi-store retailer’s data was split across POS, e-commerce, CRM, media and social. Teams could see activity but not which campaigns, channels or products were working.", zh: "一家多店零售商的資料分散於 POS、網店、CRM、媒體及社交平台。團隊看得到活動，卻看不清哪些宣傳、渠道或產品真正奏效。" },
    scope: { en: ["Data source mapping", "Connected reporting layer", "Management decision view"], zh: ["資料來源對照", "連接式報告層", "管理層決策視圖"] },
    workflowBefore: { en: ["Scattered reports checked by hand", "No shared definitions"], zh: ["人手翻查分散的報告", "沒有共同定義"] },
    workflowAfter: { en: ["Key signals unified in one view", "AI-prepared performance summaries", "Management review of budget and content shifts"], zh: ["主要訊號整合於同一視圖", "由 AI 準備成效摘要", "管理層審閱預算及內容調整"] },
    humanDecisions: { en: "The management team reviewed the reports and made final budget and campaign decisions.", zh: "管理團隊審閱報告，並作出最終預算及宣傳決定。" },
    dataFoundation: { en: "POS, e-commerce platform, CRM records, media platform APIs, social metrics.", zh: "POS、網店平台、CRM 紀錄、媒體平台介面、社交數據。" },
    outcome: { en: "Key signals now sit in one view; AI prepares the performance summaries, and management reviews budget and content shifts from them.", zh: "主要訊號整合於同一視圖；成效摘要由 AI 準備，管理層據此審閱預算及內容調整。" },
    reusable: { en: "A retail performance reporting workflow.", zh: "零售成效報告流程。" },
  }),
  client({
    slug: "ai-assisted-lead-generation", legacyId: 2,
    title: { en: "AI-assisted lead generation for a financial brand", zh: "金融品牌的 AI 輔助獲客" },
    sector: { en: "Financial services", zh: "金融服務" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["financial-services"], services: ["digitalmarketing", "crm-sales"], products: ["creativemax"],
    problem: { en: "Manual campaign optimisation and slow lead review made it hard to respond to market changes.", zh: "人手優化宣傳及緩慢的商機審閱，令團隊難以回應市場變化。" },
    scope: { en: ["Campaign intelligence", "Audience analysis", "Creative testing", "Lead quality review"], zh: ["宣傳情報", "受眾分析", "創意測試", "商機質素審閱"] },
    workflowBefore: { en: ["Optimisation done weekly by hand", "Lead quality reviewed late"], zh: ["每週人手優化", "較遲才審閱商機質素"] },
    workflowAfter: { en: ["AI flags stronger segments and creative options", "Marketing team reviews recommendations", "CRM lead records inform the next round"], zh: ["AI 標示表現較佳的受眾及創意選項", "市場團隊審閱建議", "CRM 商機紀錄為下一輪提供依據"] },
    humanDecisions: { en: "The marketing team reviewed every recommendation and made final campaign decisions.", zh: "市場團隊審閱每項建議，並作出最終宣傳決定。" },
    dataFoundation: { en: "Media platform data, CRM lead records, audience segments, creative performance.", zh: "媒體平台數據、CRM 商機紀錄、受眾分組、創意成效。" },
    outcome: { en: "AI flags the stronger segments and creative options, the marketing team reviews each recommendation, and CRM lead records feed the next round.", zh: "AI 標示表現較佳的受眾及創意選項，市場團隊逐一審閱建議，CRM 商機紀錄為下一輪提供依據。" },
    reusable: { en: "Lead-quality review and campaign optimisation workflow.", zh: "商機質素審閱及宣傳優化流程。" },
  }),
  client({
    slug: "social-commerce-growth-system", legacyId: 3,
    title: { en: "Social commerce growth system", zh: "社交電商增長系統" },
    sector: { en: "D2C e-commerce", zh: "直銷電商" }, market: { en: "Southeast Asia", zh: "東南亞" },
    industries: ["retail-ecommerce"], services: ["digitalmarketing", "koc-community", "content-creative"], products: ["creativemax", "whatsapp-aigc"],
    problem: { en: "Organic reach was declining and the brand needed content, creator coordination and learning at speed across platforms.", zh: "自然觸及下降，品牌需要在不同平台快速處理內容、協調創作者並從中學習。" },
    scope: { en: ["Content planning", "Platform-specific execution", "Creator/KOC activation", "Performance review"], zh: ["內容規劃", "按平台執行", "創作者／KOC 動員", "成效檢討"] },
    workflowBefore: { en: ["Posting without a test-and-learn loop", "Creator briefs inconsistent"], zh: ["只發布內容，未有測試及學習機制", "創作者簡報不一致"] },
    workflowAfter: { en: ["AI-assisted content calendar", "Brand-approved creator briefs", "Regular performance review"], zh: ["AI 輔助內容日程", "經品牌批准的創作者簡報", "定期成效檢討"] },
    humanDecisions: { en: "The brand team reviewed content plans, approved creator briefs and adjusted messaging.", zh: "品牌團隊審閱內容計劃、批准創作者簡報並調整訊息。" },
    dataFoundation: { en: "Social analytics, e-commerce sales, creator content performance, product catalogue.", zh: "社交分析、電商銷售、創作者內容成效、產品目錄。" },
    outcome: { en: "Content runs from an AI-assisted calendar, creators work from brand-approved briefs, and performance is reviewed on a regular cycle.", zh: "內容按 AI 輔助的日程推進，創作者依經品牌批准的簡報工作，成效定期檢討。" },
    reusable: { en: "Content calendar and creator campaign workflow.", zh: "內容日程及創作者宣傳流程。" },
  }),
  client({
    slug: "crm-loyalty-workflow-revamp", legacyId: 4,
    title: { en: "CRM and loyalty workflow revamp", zh: "CRM 及會員流程革新" },
    sector: { en: "FMCG", zh: "快速消費品" }, market: { en: "Greater Bay Area", zh: "大灣區" },
    industries: ["retail-ecommerce"], services: ["marketing-automation", "crm-sales", "customer-experience"], products: ["customer-ops"],
    problem: { en: "Loyalty data existed but was not used to create timely, relevant customer journeys.", zh: "雖有會員資料，卻未用於建立適時而相關的顧客旅程。" },
    scope: { en: ["Segmentation", "Lifecycle triggers", "Messaging workflows", "Reporting"], zh: ["顧客分組", "生命周期觸發", "訊息流程", "報告"] },
    workflowBefore: { en: ["Generic campaigns to the whole base", "Limited personalisation"], zh: ["向所有會員發送一式一樣的宣傳", "個人化有限"] },
    workflowAfter: { en: ["AI-assisted segment and trigger suggestions", "Team-approved messaging", "Performance reporting"], zh: ["AI 輔助建議分組及觸發條件", "經團隊批准的訊息", "成效報告"] },
    humanDecisions: { en: "The marketing team reviewed segments and approved messaging before deployment.", zh: "市場團隊在推出前審閱分組並批准訊息。" },
    dataFoundation: { en: "CRM records, purchase history, loyalty data, messaging engagement.", zh: "CRM 紀錄、購買記錄、會員資料、訊息互動。" },
    outcome: { en: "Segment and trigger suggestions arrive AI-assisted, every message is team-approved before it goes out, and performance is reported back.", zh: "分組及觸發條件由 AI 輔助建議，每則訊息發出前經團隊批准，成效有報告回饋。" },
    reusable: { en: "Lifecycle and retention journey templates.", zh: "生命周期及留客旅程範本。" },
  }),
  client({
    slug: "luxury-data-unification", legacyId: 5,
    title: { en: "Luxury customer data unification", zh: "奢侈品牌顧客資料整合" },
    sector: { en: "Luxury", zh: "奢侈品" }, market: { en: "Taiwan", zh: "台灣" },
    industries: ["beauty-luxury"], services: ["data-hub", "business-intelligence"], products: [],
    problem: { en: "Customer data was fragmented across boutiques, e-commerce, media and campaign tools.", zh: "顧客資料分散於專門店、網店、媒體及宣傳工具之間。" },
    scope: { en: ["First-party data connection", "Media and commerce signals", "Unified dashboards"], zh: ["連接第一方資料", "媒體及電商訊號", "統一儀表板"] },
    workflowBefore: { en: ["Channel reports viewed separately", "Unclear attribution"], zh: ["分開查看各渠道報告", "成效歸因不清"] },
    workflowAfter: { en: ["Connected touchpoint view", "Attribution and insight analysis", "Dashboards for leadership"], zh: ["連接各接觸點的視圖", "歸因及洞察分析", "供管理層使用的儀表板"] },
    humanDecisions: { en: "Marketing and management teams used the dashboards for strategic decisions.", zh: "市場及管理團隊以儀表板作策略決定。" },
    dataFoundation: { en: "First-party customer data, boutique POS, e-commerce, media APIs, campaign tools.", zh: "第一方顧客資料、專門店 POS、網店、媒體介面、宣傳工具。" },
    outcome: { en: "Touchpoints sit in one connected view, attribution and insight analysis run on it, and leadership reads the results from dashboards.", zh: "各接觸點連接於同一視圖，歸因及洞察分析以此為基礎，管理層透過儀表板查看結果。" },
    reusable: { en: "Customer insight and attribution model.", zh: "顧客洞察及歸因模型。" },
  }),
  client({
    slug: "healthcare-digital-outreach", legacyId: 6,
    title: { en: "Healthcare digital outreach with review built in", zh: "設有審閱機制的醫療數碼推廣" },
    sector: { en: "Healthcare", zh: "醫療" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["healthcare-wellness"], services: ["seo-aeo", "digitalmarketing", "content-creative"], products: ["creativemax"],
    problem: { en: "The organisation needed more awareness and patient engagement while keeping strict content standards.", zh: "機構需要提升知名度及病人參與，同時維持嚴格的內容標準。" },
    scope: { en: ["Content strategy", "SEO", "Audience targeting", "Message review"], zh: ["內容策略", "SEO", "受眾定位", "訊息審閱"] },
    workflowBefore: { en: ["Content produced ad hoc", "Review steps unclear"], zh: ["內容臨時製作", "審閱步驟不清"] },
    workflowAfter: { en: ["Planned education content", "AI-assisted compliance checks", "Professional approval before publication"], zh: ["有規劃的健康教育內容", "AI 輔助合規檢查", "發布前由專業人員批准"] },
    humanDecisions: { en: "Healthcare professionals reviewed and approved all content before publication.", zh: "所有內容在發布前均由醫護專業人員審閱及批准。" },
    dataFoundation: { en: "Website analytics, search data, social metrics, engagement data.", zh: "網站分析、搜尋數據、社交數據、互動數據。" },
    outcome: { en: "Education content is planned ahead, AI checks it for compliance, and a professional approves every piece before it is published.", zh: "健康教育內容預先規劃，由 AI 輔助合規檢查，每項內容發布前都由專業人員批准。" },
    reusable: { en: "Content review workflow for regulated topics.", zh: "受規管題材的內容審閱流程。" },
  }),
  client({
    slug: "reporting-knowledge-automation", legacyId: 7,
    title: { en: "Reporting and knowledge automation", zh: "報告及知識自動化" },
    sector: { en: "Non-profit organisation", zh: "非牟利機構" }, market: { en: "Regional", zh: "區域" },
    industries: [], services: ["workflow-automation", "business-intelligence"], products: [],
    problem: { en: "Teams spent too much time collecting updates and turning scattered project knowledge into management-ready reports.", zh: "團隊花大量時間收集進度，並把零散的項目知識整理成管理層報告。" },
    scope: { en: ["Structured inputs", "Draft report sections", "Review routing"], zh: ["結構化輸入", "草擬報告章節", "審閱分流"] },
    workflowBefore: { en: ["Updates chased by email", "Reports written from scratch"], zh: ["以電郵追收進度", "報告由零開始撰寫"] },
    workflowAfter: { en: ["Structured update collection", "AI-drafted sections", "Leads edit and approve"], zh: ["以結構化方式收集進度", "由 AI 草擬章節", "主管修改及批准"] },
    humanDecisions: { en: "Team leads and management reviewed, edited and approved every report.", zh: "每份報告均由團隊主管及管理層審閱、修改及批准。" },
    dataFoundation: { en: "Project tools, spreadsheets, document repositories, team inputs.", zh: "項目工具、試算表、文件庫、團隊輸入。" },
    outcome: { en: "Updates are collected in a structured form, AI drafts the sections, and leads edit and approve each one.", zh: "進度以結構化方式收集，章節由 AI 草擬，主管逐一修改及批准。" },
    reusable: { en: "Management briefing workflow.", zh: "管理層簡報流程。" },
  }),
  client({
    slug: "real-estate-sales-follow-up", legacyId: 8,
    title: { en: "Property sales follow-up workflow", zh: "物業銷售跟進流程" },
    sector: { en: "Real estate", zh: "地產" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["property-real-estate"], services: ["crm-sales", "whatsapp-automation", "workflow-automation"], products: ["customer-ops", "website-cms"],
    problem: { en: "Property enquiries arrived from several channels; response quality and timing varied by team, and managers could not see which leads had been followed up.", zh: "物業查詢來自多個渠道，回覆質素及時間因團隊而異，管理層亦看不到哪些商機已被跟進。" },
    scope: { en: ["Listing data connection", "Buyer requirement summaries", "Follow-up drafts", "Pipeline visibility"], zh: ["連接物業資料", "買家需要摘要", "跟進草稿", "銷售管道可視化"] },
    workflowBefore: { en: ["Each agent tracked leads personally", "No shared view of follow-up"], zh: ["每位經紀自行追蹤商機", "沒有共同的跟進視圖"] },
    workflowAfter: { en: ["Buyer summaries prepared from listing and CRM data", "Follow-up drafts for the sales owner", "Managers see pipeline status"], zh: ["根據物業及 CRM 資料準備買家摘要", "為銷售負責人準備跟進草稿", "管理層可查看銷售管道狀況"] },
    humanDecisions: { en: "Sales agents reviewed and sent every follow-up themselves; managers monitored the pipeline.", zh: "每則跟進均由經紀審閱後親自發送；管理層監察銷售管道。" },
    dataFoundation: { en: "Listing data, CRM lead records, buyer requirement forms, messaging channels.", zh: "物業資料、CRM 商機紀錄、買家需要表格、訊息渠道。" },
    outcome: { en: "Buyer summaries are prepared from listing and CRM data, the sales owner gets a follow-up draft, and managers read pipeline status from the record.", zh: "買家摘要根據物業及 CRM 資料準備，銷售負責人收到跟進草稿，管理層直接從紀錄查看銷售管道狀況。" },
    reusable: { en: "A listing-to-enquiry follow-up workflow.", zh: "由物業資料到查詢跟進的流程。" },
  }),
  client({
    slug: "hotel-guest-experience-recovery", legacyId: 9,
    title: { en: "Hotel guest experience recovery", zh: "酒店住客體驗補救" },
    sector: { en: "Hospitality", zh: "酒店" }, market: { en: "Japan", zh: "日本" },
    industries: ["hospitality-travel"], services: ["customer-experience", "social-listening"], products: ["social-listening", "customer-ops"],
    problem: { en: "Guest feedback was spread across review sites, surveys, emails and front-desk logs.", zh: "住客意見分散於評論網站、問卷、電郵及前台記錄。" },
    scope: { en: ["Feedback classification", "Urgent issue flags", "Recovery response drafts"], zh: ["意見分類", "緊急問題標示", "補救回覆草稿"] },
    workflowBefore: { en: ["Feedback read source by source", "Recovery handled case by case"], zh: ["逐個來源閱讀意見", "逐宗處理補救"] },
    workflowAfter: { en: ["Feedback classified and flagged", "Sentiment summaries", "Manager-approved recovery replies"], zh: ["意見已分類及標示", "情緒摘要", "經經理批准的補救回覆"] },
    humanDecisions: { en: "Hotel managers reviewed flagged issues and approved recovery responses before sending.", zh: "酒店經理審閱被標示的問題，並在發送前批准補救回覆。" },
    dataFoundation: { en: "Review sites, surveys, email feedback, front-desk logs, social mentions.", zh: "評論網站、問卷、電郵意見、前台記錄、社交提及。" },
    outcome: { en: "Guest feedback is classified and flagged, sentiment is summarised, and recovery replies go out only after a manager approves them.", zh: "住客意見已分類及標示，並附情緒摘要；補救回覆須經經理批准才發出。" },
    reusable: { en: "Guest review summary and recovery workflow.", zh: "住客評論摘要及補救流程。" },
  }),
  client({
    slug: "travel-koc-campaign-engine", legacyId: 10,
    title: { en: "Travel creator campaign workflow", zh: "旅遊創作者宣傳流程" },
    sector: { en: "Travel", zh: "旅遊" }, market: { en: "Regional", zh: "區域" },
    industries: ["hospitality-travel"], services: ["koc-community", "content-creative"], products: ["whatsapp-aigc"],
    problem: { en: "Scaling creator content was held back by inconsistent briefs, submission tracking, approvals and reporting.", zh: "簡報不一致、提交追蹤、批核及報告等問題，令創作者內容難以擴展。" },
    scope: { en: ["Creator recruitment", "Mission briefs", "Submission tracking", "Campaign reporting"], zh: ["招募創作者", "任務簡報", "提交追蹤", "宣傳報告"] },
    workflowBefore: { en: ["Briefs rewritten per creator", "Submissions tracked in spreadsheets"], zh: ["每位創作者重寫簡報", "以試算表追蹤提交"] },
    workflowAfter: { en: ["AI-assisted brief drafting", "Classified submissions", "Brand-approved content and reports"], zh: ["AI 輔助草擬簡報", "已分類的提交內容", "經品牌批准的內容及報告"] },
    humanDecisions: { en: "The brand team approved creator briefs, submissions and final reports.", zh: "品牌團隊批准創作者簡報、提交內容及最終報告。" },
    dataFoundation: { en: "Creator platform data, social analytics, content library, campaign calendar.", zh: "創作者平台資料、社交分析、內容庫、宣傳日程。" },
    outcome: { en: "Briefs are drafted with AI help, creator submissions arrive classified, and content and reports are brand-approved.", zh: "簡報由 AI 輔助草擬，創作者提交的內容已分類，內容及報告均經品牌批准。" },
    reusable: { en: "Creator briefing and campaign reporting workflow.", zh: "創作者簡報及宣傳報告流程。" },
  }),
  client({
    slug: "education-course-enquiry-automation", legacyId: 11,
    title: { en: "Course enquiry handling", zh: "課程查詢處理" },
    sector: { en: "Education", zh: "教育" }, market: { en: "Hong Kong", zh: "香港" },
    industries: [], services: ["customer-experience", "crm-sales", "whatsapp-automation"], products: ["customer-ops"],
    problem: { en: "Repeated questions about courses, schedules, fees and admissions created heavy manual work.", zh: "有關課程、時間表、學費及入學的重複查詢，帶來大量人手工作。" },
    scope: { en: ["Course knowledge base", "Enquiry classification", "Response drafts", "Escalation"], zh: ["課程知識庫", "查詢分類", "回覆草稿", "上報"] },
    workflowBefore: { en: ["Every question answered from scratch", "Inconsistent replies"], zh: ["每條問題都由零回答", "回覆不一致"] },
    workflowAfter: { en: ["Drafts from approved course information", "Sensitive cases routed to staff", "Approved templates"], zh: ["根據已批准的課程資料草擬", "敏感個案轉交職員", "已批准的範本"] },
    humanDecisions: { en: "Admin staff handled complex or sensitive cases and approved response templates.", zh: "行政職員處理複雜或敏感個案，並批准回覆範本。" },
    dataFoundation: { en: "Course catalogue, FAQs, CRM enquiry records, messaging logs.", zh: "課程目錄、常見問題、CRM 查詢紀錄、訊息記錄。" },
    outcome: { en: "Replies are drafted from approved course information and templates, and sensitive cases go straight to staff.", zh: "回覆根據已批准的課程資料及範本草擬，敏感個案直接轉交職員。" },
    reusable: { en: "Enquiry support workflow.", zh: "查詢支援流程。" },
  }),
  client({
    slug: "b2b-trading-supplier-intelligence", legacyId: 12,
    title: { en: "Supplier quotation comparison", zh: "供應商報價比較" },
    sector: { en: "B2B trading", zh: "企業貿易" }, market: { en: "Greater Bay Area", zh: "大灣區" },
    industries: ["b2b-professional-services"], services: ["workflow-automation", "data-hub"], products: [],
    problem: { en: "Quotations arrived by email, PDF, spreadsheet and chat; comparing them by hand was slow and missed details.", zh: "報價經電郵、PDF、試算表及聊天訊息傳來，人手比較既慢且易遺漏細節。" },
    scope: { en: ["Field extraction", "Term comparison", "Missing-information flags", "Follow-up drafts"], zh: ["擷取欄位", "比較條款", "標示缺漏資料", "跟進草稿"] },
    workflowBefore: { en: ["Manual copy into spreadsheets", "Missed terms"], zh: ["人手複製到試算表", "遺漏條款"] },
    workflowAfter: { en: ["Fields extracted for comparison", "Gaps flagged", "Team decides the supplier"], zh: ["擷取欄位作比較", "標示缺口", "由團隊決定供應商"] },
    humanDecisions: { en: "The trading team reviewed comparisons and made supplier decisions.", zh: "貿易團隊審閱比較結果並決定供應商。" },
    dataFoundation: { en: "Email archives, PDF quotations, spreadsheets, supplier database.", zh: "電郵存檔、PDF 報價、試算表、供應商資料庫。" },
    outcome: { en: "Supplier fields are extracted side by side, gaps are flagged, and the team makes the supplier decision.", zh: "供應商欄位擷取後並列比較，缺口已標示，由團隊決定供應商。" },
    reusable: { en: "Quotation comparison workflow.", zh: "報價比較流程。" },
  }),
  client({
    slug: "professional-services-proposal-drafting", legacyId: 13,
    title: { en: "Proposal first-draft support", zh: "建議書初稿支援" },
    sector: { en: "Professional services", zh: "專業服務" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["b2b-professional-services"], services: ["workflow-automation", "ai-training"], products: [],
    problem: { en: "Consultants spent too long searching past proposals and drafting from scratch.", zh: "顧問花太多時間翻查過往建議書，並由零開始撰寫。" },
    scope: { en: ["Approved knowledge search", "Relevant example matching", "Structured first drafts"], zh: ["搜尋已批准知識", "配對相關例子", "結構化初稿"] },
    workflowBefore: { en: ["Searching folders by memory", "Inconsistent structure"], zh: ["憑記憶翻查資料夾", "結構不一致"] },
    workflowAfter: { en: ["Search limited to approved material", "Structured first version", "Consultant refines"], zh: ["只搜尋已批准的資料", "結構化初稿", "由顧問修飾"] },
    humanDecisions: { en: "Consultants reviewed, refined and personalised every draft.", zh: "每份草稿均由顧問審閱、修飾及個人化。" },
    dataFoundation: { en: "Proposal library, case database, service descriptions.", zh: "建議書庫、案例資料庫、服務說明。" },
    outcome: { en: "First versions come structured from approved material only, and the consultant refines each one.", zh: "初稿只根據已批准的資料、以結構化方式產生，再由顧問逐份修飾。" },
    reusable: { en: "Knowledge search and drafting workflow.", zh: "知識搜尋及草擬流程。" },
  }),
  client({
    slug: "finance-management-reporting", legacyId: 14,
    title: { en: "Management reporting commentary", zh: "管理報告評述" },
    sector: { en: "Financial services", zh: "金融服務" }, market: { en: "Regional", zh: "區域" },
    industries: ["financial-services"], services: ["business-intelligence", "workflow-automation"], products: [],
    problem: { en: "The monthly pack required manual consolidation of spreadsheets, dashboards, budgets and variance commentary.", zh: "每月報告需要人手整合試算表、儀表板、預算及差異評述。" },
    scope: { en: ["Connected reporting files", "Change summaries", "Draft variance commentary"], zh: ["連接報告檔案", "變化摘要", "草擬差異評述"] },
    workflowBefore: { en: ["Numbers consolidated by hand", "Commentary written at the last minute"], zh: ["人手整合數字", "臨急撰寫評述"] },
    workflowAfter: { en: ["Unusual movements flagged", "Draft commentary for review", "Finance adds context"], zh: ["標示異常變動", "草擬評述供審閱", "由財務團隊補充背景"] },
    humanDecisions: { en: "The finance team reviewed summaries and added strategic context before distribution.", zh: "財務團隊在發出前審閱摘要並補充策略背景。" },
    dataFoundation: { en: "Financial spreadsheets, KPI dashboards, budget files.", zh: "財務試算表、KPI 儀表板、預算檔案。" },
    outcome: { en: "Unusual movements are flagged, commentary arrives as a draft for review, and finance adds the context.", zh: "異常變動已標示，評述以草稿形式供審閱，由財務團隊補充背景。" },
    reusable: { en: "Management pack workflow.", zh: "管理報告流程。" },
  }),
  client({
    slug: "hr-knowledge-onboarding", legacyId: 15,
    title: { en: "HR policy and onboarding knowledge", zh: "人力資源政策及入職知識" },
    sector: { en: "Professional services", zh: "專業服務" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["b2b-professional-services"], services: ["ai-training", "workflow-automation"], products: [],
    problem: { en: "HR repeatedly answered the same policy, onboarding, leave and training questions.", zh: "人力資源部反覆回答相同的政策、入職、假期及培訓問題。" },
    scope: { en: ["Approved document library", "Question answering", "Escalation of sensitive matters"], zh: ["已批准文件庫", "問答", "上報敏感事宜"] },
    workflowBefore: { en: ["Questions by email and chat", "Answers varied"], zh: ["以電郵及聊天提問", "答案不一"] },
    workflowAfter: { en: ["Answers drawn from approved documents", "Sensitive matters routed to HR", "HR reviews knowledge updates"], zh: ["答案取自已批准文件", "敏感事宜轉交人力資源部", "人力資源部審閱知識更新"] },
    humanDecisions: { en: "HR staff handled all sensitive employee matters and reviewed knowledge updates.", zh: "所有敏感僱員事宜由人力資源部處理，並由其審閱知識更新。" },
    dataFoundation: { en: "HR policies, onboarding guides, training materials, SOPs.", zh: "人事政策、入職指南、培訓資料、標準作業程序。" },
    outcome: { en: "Answers come from approved documents, sensitive matters go to HR, and HR reviews every knowledge update.", zh: "答案取自已批准文件，敏感事宜轉交人力資源部，知識更新由人力資源部審閱。" },
    reusable: { en: "Internal knowledge Q&A workflow.", zh: "內部知識問答流程。" },
  }),
  client({
    slug: "restaurant-group-local-growth", legacyId: 16,
    title: { en: "Restaurant group local visibility", zh: "餐飲集團地區曝光" },
    sector: { en: "Food & beverage", zh: "餐飲" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["food-beverage"], services: ["seo-aeo", "digitalmarketing", "social-listening"], products: ["website-cms", "creativemax"],
    problem: { en: "Each branch managed search, maps, social and review content inconsistently.", zh: "各分店處理搜尋、地圖、社交及評論內容的方式不一。" },
    scope: { en: ["Branch-level content", "Review response drafts", "Menu promotion calendar", "Local search"], zh: ["分店內容", "評論回覆草稿", "餐牌推廣日程", "地區搜尋"] },
    workflowBefore: { en: ["Branches posted independently", "Reviews answered irregularly"], zh: ["分店各自發布", "評論回覆不定期"] },
    workflowAfter: { en: ["Shared calendar with branch variants", "Drafted review responses", "Branch manager approval"], zh: ["共用日程配合分店版本", "草擬評論回覆", "分店經理批准"] },
    humanDecisions: { en: "Branch managers reviewed and approved responses and content.", zh: "分店經理審閱及批准回覆和內容。" },
    dataFoundation: { en: "Local search data, maps listings, social profiles, reviews, menus.", zh: "地區搜尋數據、地圖資料、社交專頁、評論、餐牌。" },
    outcome: { en: "Branches work from a shared calendar with their own variants, review responses arrive drafted, and the branch manager approves them.", zh: "各分店使用共用日程並有各自版本，評論回覆預先草擬，由分店經理批准。" },
    reusable: { en: "Branch content and review response workflow.", zh: "分店內容及評論回覆流程。" },
  }),
  client({
    slug: "automotive-lead-test-drive", legacyId: 17,
    title: { en: "Lead to test-drive follow-up", zh: "由商機到試車跟進" },
    sector: { en: "Automotive", zh: "汽車" }, market: { en: "Hong Kong", zh: "香港" },
    industries: [], services: ["crm-sales", "digitalmarketing"], products: ["customer-ops"],
    problem: { en: "Leads from ads, landing pages, social and showroom events were followed up inconsistently.", zh: "來自廣告、登陸頁、社交及陳列室活動的商機跟進不一致。" },
    scope: { en: ["Prospect classification", "Follow-up drafts", "CRM stage reminders"], zh: ["潛在客戶分類", "跟進草稿", "CRM 階段提醒"] },
    workflowBefore: { en: ["Follow-up depended on individuals", "Stages not updated"], zh: ["跟進取決於個人", "階段未有更新"] },
    workflowAfter: { en: ["Classified prospects", "Drafts for sales approval", "Reminders for pending actions"], zh: ["已分類的潛在客戶", "供銷售批准的草稿", "待辦事項提醒"] },
    humanDecisions: { en: "Sales teams reviewed classifications and approved messages before sending.", zh: "銷售團隊審閱分類並在發送前批准訊息。" },
    dataFoundation: { en: "Ad lead data, CRM records, landing page forms.", zh: "廣告商機資料、CRM 紀錄、登陸頁表格。" },
    outcome: { en: "Prospects arrive classified, drafts wait for sales approval, and pending actions trigger reminders.", zh: "潛在客戶已分類，草稿等待銷售批准，待辦事項會發出提醒。" },
    reusable: { en: "Lead follow-up workflow.", zh: "商機跟進流程。" },
  }),
  client({
    slug: "property-management-resident-support", legacyId: 18,
    title: { en: "Resident request routing", zh: "住戶要求分流" },
    sector: { en: "Property management", zh: "物業管理" }, market: { en: "Hong Kong", zh: "香港" },
    industries: ["property-real-estate"], services: ["customer-experience", "workflow-automation"], products: ["customer-ops"],
    problem: { en: "Requests came through forms, calls, chat and email, making prioritisation slow.", zh: "要求經表格、電話、聊天及電郵傳來，難以迅速排序。" },
    scope: { en: ["Issue classification", "Urgency detection", "Routing", "Management summaries"], zh: ["問題分類", "判斷緊急程度", "分流", "管理摘要"] },
    workflowBefore: { en: ["Requests logged by hand", "Urgent issues missed"], zh: ["人手記錄要求", "遺漏緊急問題"] },
    workflowAfter: { en: ["Classified and prioritised tasks", "Routed to the right team", "Managers handle escalations"], zh: ["已分類及排序的工作", "轉交合適團隊", "經理處理上報個案"] },
    humanDecisions: { en: "Operations managers reviewed summaries and handled escalated cases.", zh: "營運經理審閱摘要並處理上報個案。" },
    dataFoundation: { en: "Request forms, call logs, chat, email, maintenance database.", zh: "要求表格、通話記錄、聊天、電郵、維修資料庫。" },
    outcome: { en: "Resident tasks are classified, prioritised and routed to the right team, and managers handle the escalations.", zh: "住戶工作已分類、排序並轉交合適團隊，上報個案由經理處理。" },
    reusable: { en: "Request routing workflow.", zh: "要求分流流程。" },
  }),
  client({
    slug: "cross-border-market-expansion-desk", legacyId: 19,
    title: { en: "Cross-border market intelligence desk", zh: "跨境市場情報平台" },
    sector: { en: "E-commerce", zh: "電商" }, market: { en: "Cross-border", zh: "跨境" },
    industries: ["retail-ecommerce"], services: ["social-listening", "seo-aeo", "business-intelligence"], products: ["social-listening", "aiso"],
    problem: { en: "Expansion needed ongoing intelligence on local competitors, platforms, search demand and localisation risk.", zh: "拓展市場需要持續掌握當地競爭對手、平台、搜尋需求及本地化風險。" },
    scope: { en: ["Market monitoring", "Competitor summaries", "Content gap analysis", "Localised recommendations"], zh: ["市場監察", "競爭對手摘要", "內容缺口分析", "本地化建議"] },
    workflowBefore: { en: ["Ad hoc desk research per market"], zh: ["逐個市場臨時進行案頭研究"] },
    workflowAfter: { en: ["Regular market briefs", "Gap analysis", "Strategy team decides"], zh: ["定期市場簡報", "缺口分析", "由策略團隊決定"] },
    humanDecisions: { en: "The market strategy team reviewed reports and made expansion decisions.", zh: "市場策略團隊審閱報告並作出拓展決定。" },
    dataFoundation: { en: "Competitor data, search trends, listening data, platform behaviour.", zh: "競爭對手資料、搜尋趨勢、聆聽資料、平台行為。" },
    outcome: { en: "Market briefs and gap analysis arrive on a regular cycle, and the strategy team makes the call.", zh: "定期提供市場簡報及缺口分析，由策略團隊作出決定。" },
    reusable: { en: "Market intelligence brief workflow.", zh: "市場情報簡報流程。" },
  }),
  client({
    slug: "public-sector-community-feedback", legacyId: 20,
    title: { en: "Community feedback analysis", zh: "社區意見分析" },
    sector: { en: "Public sector", zh: "公營機構" }, market: { en: "Hong Kong", zh: "香港" },
    industries: [], services: ["social-listening", "business-intelligence"], products: ["social-listening"],
    problem: { en: "Feedback from surveys, events, email and social platforms took too long to analyse.", zh: "來自問卷、活動、電郵及社交平台的意見分析費時。" },
    scope: { en: ["Topic and urgency classification", "Summaries", "Governance for sensitive material"], zh: ["按主題及緊急程度分類", "摘要", "敏感資料管治"] },
    workflowBefore: { en: ["Manual reading and tagging"], zh: ["人手閱讀及標籤"] },
    workflowAfter: { en: ["Classified comments", "Draft summaries", "Public affairs review before use"], zh: ["已分類的意見", "草擬摘要", "使用前由公共事務團隊審閱"] },
    humanDecisions: { en: "The public affairs team reviewed all summaries before any public-facing use.", zh: "所有摘要在對外使用前均由公共事務團隊審閱。" },
    dataFoundation: { en: "Survey data, event feedback, emails, social comments.", zh: "問卷資料、活動意見、電郵、社交留言。" },
    outcome: { en: "Comments are classified and summarised in draft, and public affairs reviews every summary before it is used.", zh: "意見已分類並草擬摘要，每份摘要使用前都由公共事務團隊審閱。" },
    reusable: { en: "Feedback intelligence workflow.", zh: "意見情報流程。" },
  }),
];

export const caseBySlug = (slug: string) => cases.find((c) => c.slug === slug);

export const caseKindLabel: Record<CaseStudy["kind"], L> = {
  "client-work": { en: "Client work", zh: "客戶項目" },
  "internal-application": { en: "Internal application", zh: "內部應用" },
  "recorded-demonstration": { en: "Recorded demonstration", zh: "錄製示範" },
  "illustrative-sample": { en: "Illustrative sample", zh: "示例" },
};
