import type { L } from "@/lib/i18n";
import type { Industry, IndustryId } from "./types";

export const industryGroups: { id: Industry["group"]; name: L }[] = [
  { id: "consumer", name: { en: "Consumer & commerce", zh: "消費及零售" } },
  { id: "experience", name: { en: "Hospitality & experience", zh: "款待及體驗" } },
  { id: "regulated", name: { en: "Regulated & sensitive", zh: "受規管及敏感行業" } },
  { id: "b2b", name: { en: "Property & B2B", zh: "地產及企業服務" } },
];

const suggested: L = {
  en: "Suggested application. The workflow below shows how the same products are configured for this sector; it is not a report of a specific deployment.",
  zh: "建議應用。以下流程展示同一套產品如何為此行業配置，並非某一個實際部署的報告。",
};

export const industries: Industry[] = [
  {
    id: "retail-ecommerce",
    headlineAccent: { en: "a reviewed launch content pack", zh: "經審閱的新品內容套件" },
    name: { en: "Retail & E-commerce", zh: "零售及電商" },
    group: "consumer",
    featured: true,
    problem: {
      en: "Hundreds of products change every season. Product pages, campaign content and store communications fall out of step, and the team spends launch week fixing copy instead of selling.",
      zh: "每季有數以百計的產品更新。產品頁、宣傳內容及門市通訊步伐不一，團隊在新品推出週忙於修正文字，而不是專注銷售。",
    },
    sources: { en: ["Product master data", "Campaign calendar", "Brand facts and claims", "Store event details"], zh: ["產品主資料", "宣傳日程", "品牌資料及宣稱", "門市活動資料"] },
    journey: [
      { step: { en: "Product record updated", zh: "更新產品紀錄" }, product: "website-cms", copy: { en: "Fields validated; gaps flagged.", zh: "驗證欄位並標示缺漏。" } },
      { step: { en: "Launch content drafted", zh: "草擬新品內容" }, product: "creativemax", copy: { en: "Copy and visuals from the same facts.", zh: "文案及視覺均根據同一套資料。" } },
      { step: { en: "Brand and merchandising review", zh: "品牌及商品團隊審閱" }, human: true, copy: { en: "Approve, edit or return.", zh: "批准、修改或退回。" } },
      { step: { en: "Pages and campaign pack exported", zh: "匯出頁面及宣傳套件" }, product: "website-cms", copy: { en: "Change history kept.", zh: "保留變更紀錄。" } },
    ],
    reviewPoints: { en: ["Merchandiser approves product facts", "Brand manager approves campaign copy"], zh: ["商品主管批准產品資料", "品牌經理批准宣傳文案"] },
    output: { en: "Consistent product pages and a reviewed launch content pack from one set of facts.", zh: "以同一套資料製作的一致產品頁，以及經審閱的新品內容套件。" },
    transformationNeed: { en: "Agree who owns product facts and how changes flow from record to page to campaign.", zh: "確認由誰負責產品資料，以及變更如何由紀錄流向頁面再到宣傳。" },
    startingScope: { en: "One category’s product pages and its launch content.", zh: "一個類別的產品頁及其新品內容。" },
    products: ["website-cms", "creativemax", "social-listening"],
    services: ["ecommerce-growth", "content-creative", "marketing-automation"],
    members: ["kinnso", "kocmax"],
    proof: suggested,
  },
  {
    id: "financial-services",
    headlineAccent: { en: "only from approved wording", zh: "只採用已批准措辭" },
    name: { en: "Financial Services", zh: "金融服務" },
    group: "regulated",
    problem: {
      en: "Every piece of customer communication needs compliance review, so content is slow; meanwhile enquiries wait while advisers search for the approved wording.",
      zh: "每則顧客通訊都要經合規審閱，內容製作因而緩慢；同時查詢要等顧問翻查已批准的措辭才能回覆。",
    },
    sources: { en: ["Approved product wording", "Compliance rules", "Enquiry records", "Adviser routing"], zh: ["已批准的產品措辭", "合規規則", "查詢紀錄", "顧問分派規則"] },
    journey: [
      { step: { en: "Enquiry captured", zh: "記錄查詢" }, product: "customer-ops", copy: { en: "Intent and product identified.", zh: "識別查詢意圖及相關產品。" } },
      { step: { en: "Response drafted from approved wording", zh: "根據已批准措辭草擬回覆" }, product: "customer-ops", copy: { en: "No new claims introduced.", zh: "不會加入新的宣稱。" } },
      { step: { en: "Adviser and compliance check", zh: "顧問及合規檢查" }, human: true, copy: { en: "Regulated advice stays with licensed people.", zh: "受規管的建議只由持牌人士提供。" } },
      { step: { en: "Next task recorded", zh: "記錄下一步工作" }, product: "customer-ops", copy: { en: "Owner and follow-up date tracked.", zh: "追蹤負責人及跟進日期。" } },
    ],
    reviewPoints: { en: ["Licensed adviser owns any advice", "Compliance approves templates and new wording"], zh: ["任何建議由持牌顧問負責", "合規部批准範本及新措辭"] },
    output: { en: "Traceable enquiry records with responses drawn only from approved wording.", zh: "可追溯的查詢紀錄，回覆只採用已批准措辭。" },
    transformationNeed: { en: "Governance first: define human-only categories, review duties and records before any drafting starts.", zh: "先處理管治：在草擬前界定只限專人處理的類別、審閱責任及記錄方式。" },
    startingScope: { en: "One product line’s enquiries with a compliance-approved answer library.", zh: "一條產品線的查詢，配合經合規批准的答案庫。" },
    products: ["customer-ops", "creativemax"],
    services: ["crm-sales", "ai-training", "business-intelligence"],
    members: [],
    proof: suggested,
  },
  {
    id: "hospitality-travel",
    headlineAccent: { en: "reviewed destination content", zh: "目的地內容" },
    name: { en: "Hospitality & Travel", zh: "酒店及旅遊" },
    group: "experience",
    problem: {
      en: "Guests ask the same questions in several languages, reviews pile up across sites, and destination content goes stale between seasons.",
      zh: "住客以多種語言提出相同問題，各平台評論不斷累積，目的地內容在季節之間又容易過時。",
    },
    sources: { en: ["Property and room facts", "Guest FAQs", "Review exports", "Seasonal offers"], zh: ["酒店及房間資料", "住客常見問題", "評論匯出", "季節優惠"] },
    journey: [
      { step: { en: "Review themes collected", zh: "收集評論主題" }, product: "social-listening", copy: { en: "Recurring issues grouped with evidence.", zh: "把重複出現的問題連同證據歸納。" } },
      { step: { en: "AI-answer check for travel questions", zh: "檢查旅遊問題的 AI 答案" }, product: "aiso", copy: { en: "How assistants describe the property.", zh: "AI 助手如何描述酒店。" } },
      { step: { en: "Operations and marketing decide", zh: "營運及市場部決定" }, human: true, copy: { en: "Fix service issues; update content.", zh: "改善服務問題；更新內容。" } },
      { step: { en: "Offer and page content refreshed", zh: "更新優惠及頁面內容" }, product: "creativemax", copy: { en: "Multilingual drafts reviewed.", zh: "審閱多語言草稿。" } },
    ],
    reviewPoints: { en: ["Property manager confirms service fixes", "Marketing approves multilingual content"], zh: ["酒店經理確認服務改善", "市場部批准多語言內容"] },
    output: { en: "A monthly guest-feedback brief and refreshed, reviewed destination content.", zh: "每月住客意見簡報，以及經審閱更新的目的地內容。" },
    transformationNeed: { en: "Connect feedback owners across front office and marketing so insight becomes action.", zh: "連繫前堂與市場部的意見負責人，令洞察化為行動。" },
    startingScope: { en: "One property’s reviews and its top ten guest questions.", zh: "一間酒店的評論及其十大住客問題。" },
    products: ["social-listening", "aiso", "creativemax"],
    services: ["seo-aeo", "social-listening", "customer-experience"],
    members: ["kinnso", "eldage"],
    proof: suggested,
  },
  {
    id: "beauty-luxury",
    headlineAccent: { en: "behind each launch decision", zh: "每個新品決定背後的證據" },
    name: { en: "Beauty & Luxury", zh: "美容及奢侈品" },
    group: "consumer",
    problem: {
      en: "Trends move fast and creators multiply, but brand expression and product claims must stay exact in every market and every post.",
      zh: "潮流瞬息萬變，創作者愈來愈多，但每個市場、每則貼文的品牌表達及產品宣稱都必須準確無誤。",
    },
    sources: { en: ["Claims approved by regulatory/brand teams", "Trend and conversation data", "Creator submissions", "Launch briefs"], zh: ["經法規／品牌團隊批准的宣稱", "潮流及討論資料", "創作者提交內容", "新品簡報"] },
    journey: [
      { step: { en: "Trend and conversation brief", zh: "潮流及討論簡報" }, product: "social-listening", copy: { en: "Evidence-linked themes.", zh: "附證據的主題。" } },
      { step: { en: "Creator materials submitted", zh: "創作者提交素材" }, product: "whatsapp-aigc", copy: { en: "Checked against the brief.", zh: "按簡報檢查。" } },
      { step: { en: "Brand claim review", zh: "品牌宣稱審閱" }, human: true, copy: { en: "Claims checked before posting.", zh: "發布前檢查宣稱。" } },
      { step: { en: "Variants exported", zh: "匯出不同版本" }, product: "creativemax", copy: { en: "Per market and language.", zh: "按市場及語言。" } },
    ],
    reviewPoints: { en: ["Brand approves every claim", "Creator content checked against mandatories"], zh: ["每項宣稱由品牌批准", "按必要事項檢查創作者內容"] },
    output: { en: "Claim-checked creator and brand content, with the evidence behind each launch decision.", zh: "經宣稱檢查的創作者及品牌內容，並附每個新品決定背後的證據。" },
    transformationNeed: { en: "One approved-claims library shared by brand, creators and agencies.", zh: "建立一套由品牌、創作者及代理共用的已批准宣稱資料庫。" },
    startingScope: { en: "One launch with a creator programme of up to 20 creators.", zh: "一次新品推出，配合最多 20 位創作者的計劃。" },
    products: ["social-listening", "whatsapp-aigc", "creativemax"],
    services: ["koc-community", "content-creative", "social-listening"],
    members: ["adfocate", "kocmax"],
    proof: suggested,
  },
  {
    id: "food-beverage",
    headlineAccent: { en: "owned enquiries", zh: "有人負責的查詢" },
    name: { en: "Food & Beverage", zh: "餐飲" },
    group: "consumer",
    problem: {
      en: "Each outlet posts its own promotions and answers its own messages, so menus, hours and offers drift out of sync online.",
      zh: "各分店各自發布優惠、回覆訊息，令網上的餐牌、營業時間及優惠資料不一致。",
    },
    sources: { en: ["Outlet records (hours, menus)", "Promotion calendar", "Review and message history"], zh: ["分店資料（營業時間、餐牌）", "優惠日程", "評論及訊息記錄"] },
    journey: [
      { step: { en: "Outlet record updated", zh: "更新分店資料" }, product: "website-cms", copy: { en: "Hours and menu validated.", zh: "驗證營業時間及餐牌。" } },
      { step: { en: "Local content drafted", zh: "草擬地區內容" }, product: "creativemax", copy: { en: "Per outlet, same brand rules.", zh: "按分店製作，品牌規範一致。" } },
      { step: { en: "Area manager review", zh: "區域經理審閱" }, human: true, copy: { en: "Approve or return.", zh: "批准或退回。" } },
      { step: { en: "Enquiries routed", zh: "分流查詢" }, product: "customer-ops", copy: { en: "Bookings and complaints to owners.", zh: "訂座及投訴轉交負責人。" } },
    ],
    reviewPoints: { en: ["Area manager approves outlet content", "Complaints always go to a person"], zh: ["區域經理批准分店內容", "投訴一律交由專人處理"] },
    output: { en: "Accurate outlet pages, reviewed local promotions and owned enquiries.", zh: "準確的分店頁面、經審閱的地區優惠，以及有人負責的查詢。" },
    transformationNeed: { en: "Clarify what outlets can change themselves and what head office approves.", zh: "釐清哪些內容分店可自行更改、哪些須由總部批准。" },
    startingScope: { en: "Up to ten outlets' pages and one promotion cycle.", zh: "最多十間分店的頁面及一個優惠周期。" },
    products: ["website-cms", "creativemax", "customer-ops"],
    services: ["digitalmarketing", "whatsapp-automation", "content-creative"],
    members: ["50-add-oil"],
    proof: suggested,
  },
  {
    id: "property-real-estate",
    headlineAccent: { en: "feeds the page and the follow-up", zh: "同時支援頁面及跟進" },
    name: { en: "Property & Real Estate", zh: "地產及物業" },
    group: "b2b",
    featured: true,
    problem: {
      en: "Listing details live in spreadsheets, enquiries arrive from portals, forms and messages, and no one can see which buyer has been followed up — or whether the listing they asked about is still accurate.",
      zh: "物業資料存放在試算表中，查詢來自物業網站、表格及訊息；沒有人能看到哪位買家已被跟進，亦不確定對方查詢的物業資料是否仍然準確。",
    },
    sources: { en: ["Structured property records", "Approved development facts", "Enquiries from forms and portals", "Sales team routing"], zh: ["結構化物業紀錄", "已確認的樓盤資料", "來自表格及物業網站的查詢", "銷售團隊分派規則"] },
    journey: [
      { step: { en: "Property record validated", zh: "驗證物業紀錄" }, product: "website-cms", copy: { en: "Floor area, facing and availability checked; gaps flagged.", zh: "檢查實用面積、座向及供應情況，並標示缺漏。" } },
      { step: { en: "Listing content drafted and reviewed", zh: "草擬及審閱物業內容" }, product: "website-cms", copy: { en: "Page updated from the same record.", zh: "以同一份紀錄更新頁面。" } },
      { step: { en: "Enquiry linked to the listing", zh: "查詢連繫到相關物業" }, product: "customer-ops", copy: { en: "One record with owner and draft reply.", zh: "一份附負責人及回覆草稿的紀錄。" } },
      { step: { en: "Sales owner follows up", zh: "銷售負責人跟進" }, human: true, copy: { en: "Owner edits, sends and sets the next task.", zh: "負責人修改、發送並訂立下一步工作。" } },
    ],
    reviewPoints: { en: ["Listing coordinator approves record changes", "Sales owner approves every response"], zh: ["物業資料統籌批准紀錄變更", "銷售負責人批准每則回覆"] },
    output: { en: "One journey from accurate listing to owned enquiry: the same property record feeds the page and the follow-up.", zh: "由準確物業資料到有人負責的查詢，一條完整旅程：同一份物業紀錄同時支援頁面及跟進。" },
    transformationNeed: { en: "Define record ownership and enquiry service levels across sales teams before automating.", zh: "在自動化之前，先界定各銷售團隊的紀錄責任及查詢服務時限。" },
    startingScope: { en: "One development or district: listing records, page updates and enquiry follow-up.", zh: "一個樓盤或地區：物業紀錄、頁面更新及查詢跟進。" },
    products: ["website-cms", "customer-ops"],
    services: ["crm-sales", "workflow-automation", "whatsapp-automation"],
    members: [],
    proof: suggested,
  },
  {
    id: "healthcare-wellness",
    headlineAccent: { en: "clearly routed clinical enquiries", zh: "分流清晰的臨床查詢" },
    name: { en: "Healthcare & Wellness", zh: "醫療及健康" },
    group: "regulated",
    problem: {
      en: "Patients and clients need clear, consistent information, but anything clinical or sensitive must reach a qualified person — fast and without an automated guess.",
      zh: "病人及客戶需要清晰一致的資訊，但任何臨床或敏感事宜都必須迅速交到合資格人士手上，而不是由系統自動猜測回覆。",
    },
    sources: { en: ["Approved patient information", "Service and clinic records", "Enquiry categories marked human-only"], zh: ["已批准的病人資訊", "服務及診所紀錄", "標示為只限專人處理的查詢類別"] },
    journey: [
      { step: { en: "Enquiry classified", zh: "分類查詢" }, product: "customer-ops", copy: { en: "Clinical topics routed straight to people.", zh: "臨床話題直接轉交專人。" } },
      { step: { en: "Administrative reply drafted", zh: "草擬行政回覆" }, product: "customer-ops", copy: { en: "Hours, location, preparation info only.", zh: "只限營業時間、地點及準備事項。" } },
      { step: { en: "Qualified staff review", zh: "合資格員工審閱" }, human: true, copy: { en: "Clinical judgement stays human.", zh: "臨床判斷由人負責。" } },
      { step: { en: "Education content refreshed", zh: "更新衞生教育內容" }, product: "creativemax", copy: { en: "From approved sources, clinically reviewed.", zh: "取材自已批准來源，並經臨床審閱。" } },
    ],
    reviewPoints: { en: ["Clinical content reviewed by qualified staff", "Sensitive categories never auto-drafted"], zh: ["臨床內容由合資格員工審閱", "敏感類別一律不自動草擬"] },
    output: { en: "Faster administrative responses and clearly routed clinical enquiries.", zh: "更快的行政回覆，以及分流清晰的臨床查詢。" },
    transformationNeed: { en: "Privacy and escalation rules agreed before any workflow runs.", zh: "在任何流程運作前，先議定私隱及上報規則。" },
    startingScope: { en: "Administrative enquiries for one clinic or service line.", zh: "一間診所或一條服務線的行政查詢。" },
    products: ["customer-ops", "creativemax"],
    services: ["customer-experience", "seo-aeo", "data-hub"],
    members: ["50-add-oil"],
    proof: suggested,
  },
  {
    id: "b2b-professional-services",
    headlineAccent: { en: "reviewed insight content", zh: "經審閱的觀點內容" },
    name: { en: "B2B & Professional Services", zh: "企業及專業服務" },
    group: "b2b",
    featured: true,
    problem: {
      en: "Expertise sits in people’s heads and past proposals. Enquiries wait while partners are busy, and thought leadership is published irregularly.",
      zh: "專業知識存在於同事腦海及過往建議書之中；合夥人忙碌時查詢便要等待，專業觀點文章亦未能定期發布。",
    },
    sources: { en: ["Service descriptions and credentials", "Past proposals (approved for reuse)", "Enquiry records", "Expert interviews"], zh: ["服務說明及資歷", "過往建議書（已批准重用）", "查詢紀錄", "專家訪談"] },
    journey: [
      { step: { en: "Enquiry qualified", zh: "評估查詢" }, product: "customer-ops", copy: { en: "Need, sector and urgency recorded.", zh: "記錄需要、行業及緊急程度。" } },
      { step: { en: "First response drafted", zh: "草擬首次回覆" }, product: "customer-ops", copy: { en: "From approved service descriptions.", zh: "取材自已批准的服務說明。" } },
      { step: { en: "Partner decides", zh: "合夥人決定" }, human: true, copy: { en: "Edits, sends, sets next step.", zh: "修改、發送並訂立下一步。" } },
      { step: { en: "Insight article prepared", zh: "準備觀點文章" }, product: "creativemax", copy: { en: "From expert interview notes, reviewed.", zh: "根據專家訪談筆記撰寫並經審閱。" } },
    ],
    reviewPoints: { en: ["Partner approves client communication", "Expert approves published opinions"], zh: ["合夥人批准客戶通訊", "專家批准發布的觀點"] },
    output: { en: "Owned enquiries with timely first responses, and a steady cadence of reviewed insight content.", zh: "有人負責、及時回覆的查詢，以及穩定發布、經審閱的觀點內容。" },
    transformationNeed: { en: "Capture reusable knowledge with clear permission for reuse.", zh: "在清晰的重用許可下，整理可重用的專業知識。" },
    startingScope: { en: "One practice area’s enquiries and a monthly insight article.", zh: "一個業務範疇的查詢及每月一篇觀點文章。" },
    products: ["customer-ops", "creativemax", "aiso"],
    services: ["crm-sales", "seo-aeo", "ai-training"],
    members: ["aip"],
    proof: suggested,
  },
];

export const industryById = (id: IndustryId) => industries.find((i) => i.id === id)!;
