import type { L } from "@/lib/i18n";
import type { IndustryId, ResourceFormat, ResourceTopic, ServiceId, SolutionId, WorkstreamId } from "./types";

export const resourceFormats: { id: ResourceFormat; name: L; plural: L }[] = [
  { id: "article", name: { en: "Article", zh: "文章" }, plural: { en: "Insights & Articles", zh: "洞察與文章" } },
  { id: "guide", name: { en: "Guide", zh: "指南" }, plural: { en: "Guides & Playbooks", zh: "指南與實務手冊" } },
  { id: "video", name: { en: "Video", zh: "影片" }, plural: { en: "Videos & Demos", zh: "影片與示範" } },
  { id: "event", name: { en: "Event", zh: "活動" }, plural: { en: "Events", zh: "活動" } },
  { id: "workshop", name: { en: "Workshop", zh: "工作坊" }, plural: { en: "Workshops & Training", zh: "工作坊與培訓" } },
];

export const resourceTopics: { id: ResourceTopic; name: L }[] = [
  { id: "ai-transformation", name: { en: "AI & transformation", zh: "AI 與轉型" } },
  { id: "search-visibility", name: { en: "Search & AI visibility", zh: "搜尋與 AI 曝光" } },
  { id: "customer-crm", name: { en: "CRM & automation", zh: "CRM 與自動化" } },
  { id: "data-intelligence", name: { en: "Data & insight", zh: "數據與洞察" } },
  { id: "commerce", name: { en: "E-commerce", zh: "電子商務" } },
  { id: "creators-community", name: { en: "Creators & community", zh: "創作者與社群" } },
  { id: "marketing-channels", name: { en: "Content & channels", zh: "內容與渠道" } },
  { id: "company-news", name: { en: "Culture, careers & news", zh: "文化、職涯與消息" } },
];

/** Links from resource topics to the most relevant commercial destinations. */
export const topicRelations: Record<ResourceTopic, { solution?: SolutionId; service?: ServiceId; workstream?: WorkstreamId }> = {
  "ai-transformation": { workstream: "ai-readiness-maturity", service: "ai-training" },
  "search-visibility": { solution: "market-intelligence", service: "seo-aeo" },
  "customer-crm": { solution: "customer-engagement", service: "crm-sales" },
  "data-intelligence": { solution: "market-intelligence", service: "business-intelligence" },
  commerce: { solution: "website-operations", service: "ecommerce-growth" },
  "creators-community": { service: "koc-community" },
  "marketing-channels": { solution: "content-production", service: "digitalmarketing" },
  "company-news": {},
};

export type Guide = {
  slug: string;
  title: L;
  summary: L;
  topic: ResourceTopic;
  published: string;
  file: Record<"en" | "zh-hant", { href: string; bytesLabel: string }>;
  format: L;
  related: { workstream?: WorkstreamId; service?: ServiceId; industry?: IndustryId };
  contents: L<string[]>;
};

/** New downloadable guides created for this site (files generated by scripts/build-guides.mjs). */
export const guides: Guide[] = [
  {
    slug: "ai-readiness-checklist",
    title: { en: "AI readiness checklist", zh: "AI 準備度清單" },
    summary: {
      en: "A practical checklist for leadership teams: value, workflow, data, systems, people and governance questions to answer before committing to an AI workflow. Indicative self-assessment — not a diagnosis.",
      zh: "供管理團隊使用的實用清單：在投入 AI 流程前，需要回答的價值、流程、資料、系統、人員及管治問題。屬參考性自我評估，並非診斷。",
    },
    topic: "ai-transformation",
    published: "2026-09-28",
    file: {
      en: { href: "/downloads/fimmick-ai-readiness-checklist-en.pdf", bytesLabel: "PDF" },
      "zh-hant": { href: "/downloads/fimmick-ai-readiness-checklist-zh-hant.pdf", bytesLabel: "PDF" },
    },
    format: { en: "PDF checklist, 2 pages", zh: "PDF 清單，2 頁" },
    related: { workstream: "ai-readiness-maturity", service: "ai-transformation" },
    contents: {
      en: ["Six readiness areas with guiding questions", "A simple 1–3 rating guide and what each rating means", "A worked sample row (labelled sample)", "What to bring to a first conversation"],
      zh: ["六個準備度範疇及引導問題", "簡單的 1–3 評級指引及其意義", "一行已完成的示例（已標示為示例）", "首次會面前可準備的資料"],
    },
  },
  {
    slug: "workflow-planning-worksheet",
    title: { en: "Workflow planning worksheet", zh: "流程規劃工作紙" },
    summary: {
      en: "A one-workflow worksheet: trigger, inputs, AI-prepared tasks, human decisions, exceptions, outputs and records. Use it to describe a workflow before discussing automation.",
      zh: "針對單一流程的工作紙：觸發點、輸入、AI 準備的任務、人手決策、例外、輸出及記錄。可在討論自動化之前，先用它描述流程。",
    },
    topic: "ai-transformation",
    published: "2026-09-28",
    file: {
      en: { href: "/downloads/fimmick-workflow-planning-worksheet-en.pdf", bytesLabel: "PDF" },
      "zh-hant": { href: "/downloads/fimmick-workflow-planning-worksheet-zh-hant.pdf", bytesLabel: "PDF" },
    },
    format: { en: "PDF worksheet, 2 pages", zh: "PDF 工作紙，2 頁" },
    related: { workstream: "workflow-agent-design", service: "workflow-automation" },
    contents: {
      en: ["Blank worksheet for one workflow", "A completed sample (the reusable-bottle content workflow, labelled sample)", "Checklist of human decision points", "Common exceptions to plan for"],
      zh: ["單一流程的空白工作紙", "已填寫的示例（可重用水樽內容流程，已標示為示例）", "人手決策點清單", "需預先規劃的常見例外"],
    },
  },
];

export const explainerVideo = {
  slug: "fimmick-aip-explainer",
  title: { en: "From brief to reviewed output: a FIMMICK AIP workflow", zh: "由簡報到經審閱的成果：FIMMICK AIP 流程示範" } as L,
  summary: {
    en: "A 42-second product demonstration using the same sample data as the interactive examples: brand facts, a prepared draft, a reviewer’s decision, an export and its record.",
    zh: "一段 42 秒的產品示範，使用與互動示例相同的示例資料：品牌資料、準備好的草稿、審閱人的決定、匯出及其記錄。",
  } as L,
  mode: { en: "Illustrative workflow — sample data. Rendered from the website’s sample interface; no live AI run, message or system update is shown.", zh: "流程示範·示例資料。由網站示例介面製作，片中並無實際 AI 運行、訊息發送或系統更新。" } as L,
  published: "2026-09-28",
  durationSeconds: 42,
  topic: "ai-transformation" as ResourceTopic,
};

export const workshopResource = {
  slug: "workshop",
  title: { en: "AI Transformation Workshop for leadership teams", zh: "管理團隊 AI 轉型工作坊" } as L,
  summary: { en: "A facilitated working session to choose a first workflow, agree review points and leave with a practical next step. Requests are confirmed by the FIMMICK team; submitting a request is not a booking.", zh: "由導師主持的工作坊，協助選出首個流程、議定審閱環節，並帶走實際可行的下一步。提交申請後由 FIMMICK 團隊確認，提交申請並不等於已預約。" } as L,
  topic: "ai-transformation" as ResourceTopic,
};
