import type { L } from "@/lib/i18n";
import type { Service, ServiceId, ServiceObjective } from "./types";

export const objectives: { id: ServiceObjective; name: L; question: L }[] = [
  { id: "acquire", name: { en: "Acquire", zh: "獲客" }, question: { en: "Reach and attract the right people", zh: "接觸並吸引合適的對象" } },
  { id: "convert", name: { en: "Convert", zh: "轉化" }, question: { en: "Turn interest into sales conversations", zh: "把興趣轉化為銷售機會" } },
  { id: "retain", name: { en: "Retain", zh: "留客" }, question: { en: "Serve and keep customers", zh: "服務及留住顧客" } },
  { id: "understand", name: { en: "Understand", zh: "洞察" }, question: { en: "See what is happening and why", zh: "了解發生了甚麼及原因" } },
  { id: "automate", name: { en: "Automate", zh: "自動化" }, question: { en: "Take repeated work off people’s plates", zh: "減少重複性的人手工作" } },
  { id: "scale", name: { en: "Scale", zh: "擴展" }, question: { en: "Build lasting capability", zh: "建立長遠能力" } },
];

const p = (en: string, zh: string) => ({ title: { en, zh } });

export const services: Service[] = [
  {
    id: "ai-transformation",
    headlineAccent: { en: "lead the change", zh: "帶領轉變" },
    objective: "scale",
    name: { en: "AI Transformation", zh: "AI 轉型" },
    eyebrow: { en: "Plan and lead the change", zh: "規劃及帶領轉變" },
    summary: { en: "Readiness, roadmap, workflow design and governance — delivered as a leadership programme.", zh: "準備度評估、路線圖、流程設計及管治——以管理層計劃形式推行。" },
    problem: { en: "AI activity is happening everywhere except in a plan the leadership team can steer.", zh: "AI 應用四處發生，唯獨沒有一個管理層可以主導的計劃。" },
    deliverables: { en: ["Readiness heatmap", "Prioritised roadmap", "Workflow blueprints", "Governance and adoption plan"], zh: ["準備度熱圖", "優先路線圖", "流程藍圖", "管治及推行計劃"] },
    inputs: { en: ["Leadership objectives", "Workflow inventory", "Systems and data map", "Policies"], zh: ["管理層目標", "流程清單", "系統及資料地圖", "政策"] },
    process: [
      { ...p("Assess readiness", "評估準備度"), copy: { en: "Build the fact base.", zh: "建立事實基礎。" } },
      { ...p("Set the roadmap", "制定路線圖"), copy: { en: "Sequence the workflows.", zh: "為流程排序。" } },
      { ...p("Design workflows", "設計流程"), copy: { en: "Define tasks and approvals.", zh: "界定任務及批核。" } },
      { ...p("Govern and adopt", "管治及推行"), copy: { en: "Train, measure, improve.", zh: "培訓、衡量、改善。" } },
    ],
    aiRole: { en: "Helps analyse workflow inventories and draft artefacts for review.", zh: "協助分析流程清單及草擬文件供審閱。" },
    specialistRole: { en: "FIMMICK consultants run interviews, facilitate decisions and write recommendations.", zh: "FIMMICK 顧問負責訪談、引導決策及撰寫建議。" },
    reviewResponsibility: { en: "Your leadership team confirms findings and owns every decision.", zh: "由你的管理團隊確認評估結果，並負責所有決定。" },
    included: { en: ["Workshops and interviews", "Written decision artefacts", "Handover to delivery teams"], zh: ["工作坊及訪談", "書面決策文件", "移交執行團隊"] },
    excluded: { en: ["Software licences", "Delivery of every roadmap item (scoped separately)"], zh: ["軟件授權", "路線圖上每項工作的執行（另行界定）"] },
    thirdParty: { en: "Recommendations may involve third-party tools; their terms remain with those vendors.", zh: "建議或涉及第三方工具，相關條款由供應商負責。" },
    sample: { label: { en: "Sample roadmap row", zh: "路線圖示例行" }, rows: { en: [["Workflow", "Enquiry follow-up"], ["Owner", "Head of Sales"], ["Dependency", "Answer library approved"], ["Decision gate", "Review after first month of records"]], zh: [["流程", "查詢跟進"], ["負責人", "銷售主管"], ["依賴條件", "答案庫已批准"], ["決策關卡", "首月紀錄完成後檢討"]] } },
    startingScope: { en: "A readiness assessment for one business unit.", zh: "為一個業務單位進行準備度評估。" },
    products: [],
    industries: ["financial-services", "b2b-professional-services", "retail-ecommerce"],
    members: ["aip"],
    workstream: "ai-readiness-maturity",
    canonicalPath: "/ai-transformation",
  },
  {
    id: "digitalmarketing",
    headlineAccent: { en: "as one system", zh: "一體化運作" },
    objective: "acquire",
    name: { en: "Digital Marketing", zh: "數碼營銷" },
    eyebrow: { en: "Campaigns that run as one system", zh: "一體化運作的宣傳" },
    summary: { en: "Campaign strategy, paid and organic delivery, creative and reporting within an agreed operating scope.", zh: "在議定範圍內提供宣傳策略、付費及自然流量執行、創意製作及報告。" },
    problem: { en: "Channels are planned separately, creative arrives late, and reports explain last month rather than guiding next week.", zh: "各渠道分開規劃，創意素材遲交，報告只解釋上月情況，未能指引下週行動。" },
    deliverables: { en: ["Campaign plan and channel mix", "Paid and organic execution", "Creative and copy production", "Performance reporting with next actions"], zh: ["宣傳計劃及渠道組合", "付費及自然流量執行", "創意及文案製作", "附下一步行動的成效報告"] },
    inputs: { en: ["Business objective and budget", "Brand guidelines", "Audience and past performance", "Access to ad accounts"], zh: ["業務目標及預算", "品牌指引", "受眾及過往成效", "廣告帳戶存取權"] },
    process: [
      { ...p("Plan", "規劃"), copy: { en: "Objective, audience, channels, measures.", zh: "目標、受眾、渠道、指標。" } },
      { ...p("Produce", "製作"), copy: { en: "Creative and copy for each channel.", zh: "各渠道的創意及文案。" } },
      { ...p("Run", "執行"), copy: { en: "Launch, monitor and optimise.", zh: "推出、監察及優化。" } },
      { ...p("Report", "報告"), copy: { en: "What happened and what to change.", zh: "發生了甚麼、要改變甚麼。" } },
    ],
    aiRole: { en: "Prepares copy variants, summarises performance and flags anomalies.", zh: "準備文案版本、總結成效及標示異常。" },
    specialistRole: { en: "Strategists, media specialists and creatives plan, buy and produce.", zh: "策略師、媒體專家及創意團隊負責規劃、投放及製作。" },
    reviewResponsibility: { en: "You approve plans, creative and material budget changes.", zh: "由你批准計劃、創意及重大預算變動。" },
    included: { en: ["Agreed channels and deliverables", "Monthly reporting"], zh: ["議定的渠道及交付項目", "每月報告"] },
    excluded: { en: ["Media spend (billed separately)", "Channels not in the agreed scope"], zh: ["媒體費用（另行收費）", "議定範圍以外的渠道"] },
    thirdParty: { en: "Ad platforms' policies and reporting limits apply.", zh: "須遵守廣告平台的政策及報告限制。" },
    sample: { label: { en: "Sample weekly action list", zh: "每週行動清單示例" }, rows: { en: [["Observation", "Carousel ads outperform single image on saves"], ["Action", "Prepare two new carousel variants"], ["Owner", "Content lead"], ["Approval", "Brand manager"]], zh: [["觀察", "輪播廣告的收藏數高於單圖廣告"], ["行動", "準備兩款新輪播版本"], ["負責人", "內容主管"], ["批核", "品牌經理"]] } },
    startingScope: { en: "One campaign across up to three channels for one market.", zh: "一個市場、最多三個渠道的一次宣傳。" },
    products: ["creativemax", "social-listening"],
    industries: ["retail-ecommerce", "food-beverage", "beauty-luxury"],
    members: ["adfocate", "kocmax"],
  },
  {
    id: "marketing-automation",
    headlineAccent: { en: "that keep running", zh: "持續運作" },
    objective: "automate",
    name: { en: "Marketing Automation", zh: "營銷自動化" },
    eyebrow: { en: "Lifecycle journeys that keep running", zh: "持續運作的顧客旅程" },
    summary: { en: "Journey and trigger design, permitted channels, lifecycle content, testing and handover.", zh: "設計旅程及觸發條件、界定獲准渠道、製作生命周期內容、測試及移交。" },
    problem: { en: "Welcome, reminder and win-back messages are sent manually, late or not at all.", zh: "歡迎、提醒及挽回訊息靠人手發送，不是太遲就是沒有發送。" },
    deliverables: { en: ["Journey map with triggers", "Message content per step", "Configured automations in your platform", "Test results and handover guide"], zh: ["附觸發條件的旅程地圖", "每一步的訊息內容", "在你平台上設定的自動化流程", "測試結果及移交指南"] },
    inputs: { en: ["Customer lifecycle data", "Consent records", "Brand content rules", "Access to your automation platform"], zh: ["顧客生命周期資料", "同意紀錄", "品牌內容規範", "自動化平台存取權"] },
    process: [
      { ...p("Map journeys", "描繪旅程"), copy: { en: "Triggers, timing and audiences.", zh: "觸發條件、時機及受眾。" } },
      { ...p("Write content", "撰寫內容"), copy: { en: "Messages for each step.", zh: "每一步的訊息。" } },
      { ...p("Build and test", "建置及測試"), copy: { en: "Configure and test in your platform.", zh: "在你的平台設定及測試。" } },
      { ...p("Hand over", "移交"), copy: { en: "Train owners, agree reviews.", zh: "培訓負責人，議定檢討安排。" } },
    ],
    aiRole: { en: "Drafts message variants and summarises journey performance.", zh: "草擬訊息版本及總結旅程成效。" },
    specialistRole: { en: "CRM specialists design journeys and configure platforms.", zh: "CRM 專家設計旅程及設定平台。" },
    reviewResponsibility: { en: "You approve every message and consent rule before activation.", zh: "啟動前，由你批准每則訊息及同意規則。" },
    included: { en: ["Agreed journeys", "Configuration in supported platforms"], zh: ["議定的旅程", "在支援平台上的設定"] },
    excluded: { en: ["Platform licences", "Messaging to contacts without valid consent"], zh: ["平台授權費", "向未有有效同意的聯絡人發送訊息"] },
    thirdParty: { en: "Depends on your email, messaging or CRM platform’s capabilities.", zh: "視乎你的電郵、訊息或 CRM 平台功能。" },
    sample: { label: { en: "Sample journey step", zh: "旅程步驟示例" }, rows: { en: [["Trigger", "No purchase 60 days after first order"], ["Channel", "Email (consented)"], ["Content", "Care tips + new colour launch"], ["Exit", "Purchase or unsubscribe"]], zh: [["觸發條件", "首次購買後 60 日未再購買"], ["渠道", "電郵（已同意）"], ["內容", "保養小貼士＋新顏色推出"], ["退出條件", "購買或取消訂閱"]] } },
    startingScope: { en: "Two lifecycle journeys on one channel.", zh: "一個渠道上的兩條生命周期旅程。" },
    products: ["creativemax", "customer-ops"],
    industries: ["retail-ecommerce", "beauty-luxury", "food-beverage"],
    members: [],
  },
  {
    id: "crm-sales",
    headlineAccent: { en: "has an owner", zh: "都有負責人" },
    objective: "convert",
    name: { en: "CRM & Sales Automation", zh: "CRM 與銷售自動化" },
    eyebrow: { en: "Every lead has an owner", zh: "每個商機都有負責人" },
    summary: { en: "Record structure, ownership, routing, follow-up and supported integrations.", zh: "設計紀錄結構、負責人、分派、跟進及支援的系統串接。" },
    problem: { en: "Leads are split across inboxes and spreadsheets; follow-up depends on who remembers.", zh: "商機分散在不同收件箱及試算表中，跟進與否取決於有沒有人記得。" },
    deliverables: { en: ["CRM record structure and stages", "Routing and ownership rules", "Follow-up templates and tasks", "Pipeline reporting"], zh: ["CRM 紀錄結構及階段", "分派及負責規則", "跟進範本及工作", "銷售管道報告"] },
    inputs: { en: ["Lead sources", "Sales process and stages", "Team and territories", "CRM access"], zh: ["商機來源", "銷售流程及階段", "團隊及負責區域", "CRM 存取權"] },
    process: [
      { ...p("Map the pipeline", "描繪銷售管道"), copy: { en: "Sources, stages, owners.", zh: "來源、階段、負責人。" } },
      { ...p("Structure records", "整理紀錄"), copy: { en: "Fields, rules, duplicates.", zh: "欄位、規則、重複紀錄。" } },
      { ...p("Automate follow-up", "自動化跟進"), copy: { en: "Tasks, reminders, drafts.", zh: "工作、提醒、草稿。" } },
      { ...p("Report", "報告"), copy: { en: "Pipeline and response times.", zh: "銷售管道及回應時間。" } },
    ],
    aiRole: { en: "Suggests routing, drafts follow-ups from approved answers and summarises pipeline changes.", zh: "建議分派、根據已確認答案草擬跟進內容，並總結銷售管道變化。" },
    specialistRole: { en: "CRM consultants design the structure and configure the platform.", zh: "CRM 顧問設計結構並設定平台。" },
    reviewResponsibility: { en: "Sales owners approve outreach and stage changes.", zh: "由銷售負責人批准外展及階段變更。" },
    included: { en: ["Configuration in a supported CRM", "Team training"], zh: ["在支援的 CRM 中設定", "團隊培訓"] },
    excluded: { en: ["CRM licences", "Unconsented outreach"], zh: ["CRM 授權費", "未經同意的外展"] },
    thirdParty: { en: "Integration depth depends on your CRM’s APIs and plan.", zh: "串接深度視乎你的 CRM 介面及方案。" },
    sample: { label: { en: "Sample routing rule", zh: "分派規則示例" }, rows: { en: [["Source", "Website enquiry — property viewing"], ["Owner", "District sales team"], ["Response target", "Same business day"], ["Escalation", "Team lead if untouched by 5pm"]], zh: [["來源", "網站查詢——睇樓預約"], ["負責人", "所屬地區銷售團隊"], ["回應目標", "同一個工作天"], ["上報", "下午五時前未處理則轉交組長"]] } },
    startingScope: { en: "One lead source, one team, one pipeline.", zh: "一個商機來源、一個團隊、一條銷售管道。" },
    products: ["customer-ops"],
    industries: ["property-real-estate", "financial-services", "b2b-professional-services"],
    members: [],
    workstream: "workflow-agent-design",
  },
  {
    id: "seo-aeo",
    headlineAccent: { en: "and AI answers", zh: "AI 答案" },
    objective: "acquire",
    name: { en: "SEO, GEO & AEO", zh: "SEO、GEO 與 AEO" },
    eyebrow: { en: "Found in search and AI answers", zh: "在搜尋及 AI 答案中被發現" },
    summary: { en: "Search and content improvements plus defined AI-answer visibility checks.", zh: "搜尋及內容改善，加上有明確範圍的 AI 答案曝光檢查。" },
    problem: { en: "Pages are hard for search engines and AI assistants to understand, so competitors get cited instead.", zh: "網頁難以被搜尋引擎及 AI 助手理解，結果引用的都是競爭對手。" },
    deliverables: { en: ["Technical and content audit", "Prioritised fix list", "Answer-ready page content", "AI-answer check for defined questions (via AISO)"], zh: ["技術及內容審核", "按優先次序排列的修正清單", "適合被 AI 引用的頁面內容", "既定問題的 AI 答案檢查（透過 AISO）"] },
    inputs: { en: ["Website access", "Priority products or services", "Search console data", "Approved facts"], zh: ["網站存取權", "重點產品或服務", "Search Console 資料", "已確認資料"] },
    process: [
      { ...p("Audit", "審核"), copy: { en: "Technical health and content gaps.", zh: "技術狀況及內容缺口。" } },
      { ...p("Prioritise", "排序"), copy: { en: "Fixes ranked by effort and value.", zh: "按工作量及價值排列修正項目。" } },
      { ...p("Improve", "改善"), copy: { en: "Pages, structure and structured data.", zh: "頁面、結構及結構化資料。" } },
      { ...p("Check", "檢查"), copy: { en: "Search and AI-answer review on a date.", zh: "按日期檢視搜尋及 AI 答案。" } },
    ],
    aiRole: { en: "Drafts content improvements and runs the defined AI-answer checks.", zh: "草擬內容改善，並執行既定的 AI 答案檢查。" },
    specialistRole: { en: "SEO specialists audit, prioritise and implement.", zh: "SEO 專家負責審核、排序及執行。" },
    reviewResponsibility: { en: "You approve page changes and factual claims.", zh: "由你批准頁面改動及事實宣稱。" },
    included: { en: ["Audit and fix list", "Agreed page improvements"], zh: ["審核及修正清單", "議定的頁面改善"] },
    excluded: { en: ["Guaranteed rankings or AI citations", "Link buying"], zh: ["保證排名或被 AI 引用", "購買連結"] },
    thirdParty: { en: "Search engines and AI assistants change independently of us.", zh: "搜尋引擎及 AI 助手的變化不受我們控制。" },
    sample: { label: { en: "Sample fix list item", zh: "修正清單示例" }, rows: { en: [["Page", "Product page — reusable bottle"], ["Issue", "Capacity and material not stated in text"], ["Fix", "Add facts table and FAQ"], ["Priority", "High — low effort"]], zh: [["頁面", "產品頁——可重用水樽"], ["問題", "文字中沒有列明容量及物料"], ["修正", "加入規格表及常見問題"], ["優先次序", "高——工作量低"]] } },
    startingScope: { en: "An audit and fix list for up to 50 priority pages.", zh: "為最多 50 個重點頁面進行審核並提供修正清單。" },
    products: ["aiso"],
    industries: ["hospitality-travel", "b2b-professional-services", "healthcare-wellness"],
    members: [],
  },
  {
    id: "social-listening",
    headlineAccent: { en: "public conversation", zh: "公開討論" },
    objective: "understand",
    name: { en: "Social Listening", zh: "社交聆聽" },
    eyebrow: { en: "Evidence from public conversation", zh: "來自公開討論的證據" },
    summary: { en: "Monitoring scope, source permissions, interpretation, reporting and follow-up.", zh: "界定監察範圍及來源權限，並提供解讀、報告及跟進。" },
    problem: { en: "Teams react to whatever gets screenshotted instead of what the evidence shows.", zh: "團隊只對被截圖轉發的內容作出反應，而不是根據證據行事。" },
    deliverables: { en: ["Monitoring set-up", "Insight briefs with linked evidence", "Alert review", "Recommendations workshop"], zh: ["監察設定", "附證據連結的洞察簡報", "警示審閱", "建議工作坊"] },
    inputs: { en: ["Brands, competitors and topics", "Markets and languages", "Decision the insight should inform"], zh: ["品牌、競爭對手及話題", "市場及語言", "洞察要支援的決策"] },
    process: [
      { ...p("Scope", "界定範圍"), copy: { en: "Topics, sources, permissions.", zh: "話題、來源、權限。" } },
      { ...p("Monitor", "監察"), copy: { en: "Collect and classify.", zh: "收集及分類。" } },
      { ...p("Interpret", "解讀"), copy: { en: "Analysts review and explain.", zh: "分析師審閱及解釋。" } },
      { ...p("Act", "行動"), copy: { en: "Recommendations and follow-up.", zh: "建議及跟進。" } },
    ],
    aiRole: { en: "Groups mentions, drafts summaries and links evidence (AI Social Listening).", zh: "歸納提及內容、草擬摘要及連結證據（AI Social Listening）。" },
    specialistRole: { en: "FIMMICK analysts interpret, prioritise and present.", zh: "FIMMICK 分析師負責解讀、排序及匯報。" },
    reviewResponsibility: { en: "Analysts sign off every brief; you decide actions.", zh: "每份簡報由分析師確認；行動由你決定。" },
    included: { en: ["Agreed topics and sources", "Regular briefs"], zh: ["議定的話題及來源", "定期簡報"] },
    excluded: { en: ["Private data", "Community management replies"], zh: ["私人資料", "社群管理回覆"] },
    thirdParty: { en: "Coverage depends on the licensed listening provider and platform access.", zh: "覆蓋範圍視乎授權聆聽供應商及平台存取情況。" },
    sample: { label: { en: "Sample insight line", zh: "洞察示例" }, rows: { en: [["Theme", "Leak-proof lids"], ["Evidence", "Linked posts (sample)"], ["Interpretation", "Commuters worry about bags"], ["Suggested action", "Lead with lid test in next content"]], zh: [["主題", "防漏杯蓋"], ["證據", "已連結貼文（示例）"], ["解讀", "通勤人士擔心弄濕手袋"], ["建議行動", "下一輪內容以杯蓋測試為重點"]] } },
    startingScope: { en: "One brand, three competitors, one market, monthly brief.", zh: "一個品牌、三個競爭對手、一個市場，每月簡報。" },
    products: ["social-listening"],
    industries: ["beauty-luxury", "food-beverage", "hospitality-travel"],
    members: ["kocmax"],
  },
  {
    id: "koc-community",
    headlineAccent: { en: "as a workflow", zh: "以流程方式運作" },
    objective: "acquire",
    name: { en: "Influencer, KOL & KOC", zh: "網紅、KOL 與 KOC" },
    eyebrow: { en: "Creator programmes run as a workflow", zh: "以流程方式運作的創作者計劃" },
    summary: { en: "Selection, briefing, review, programme delivery and measurement.", zh: "創作者篩選、簡報、內容審閱、計劃執行及成效衡量。" },
    problem: { en: "Creators are chosen by follower count, briefs are inconsistent and reports are screenshots.", zh: "以粉絲數目挑選創作者，簡報不一致，報告只有截圖。" },
    deliverables: { en: ["Creator shortlist with fit notes", "Brief and content checklist", "Content review workflow", "Programme report"], zh: ["附適配說明的創作者名單", "簡報及內容檢查清單", "內容審閱流程", "計劃報告"] },
    inputs: { en: ["Campaign objective and audience", "Brand guidelines and mandatories", "Budget and timing"], zh: ["宣傳目標及受眾", "品牌指引及必要事項", "預算及時間"] },
    process: [
      { ...p("Select", "篩選"), copy: { en: "Fit, audience and brand safety.", zh: "適配度、受眾及品牌安全。" } },
      { ...p("Brief", "簡報"), copy: { en: "Clear mandatories and checklist.", zh: "清晰的必要事項及清單。" } },
      { ...p("Review", "審閱"), copy: { en: "Content checked before posting.", zh: "發布前檢查內容。" } },
      { ...p("Measure", "衡量"), copy: { en: "Results against the objective.", zh: "按目標衡量成效。" } },
    ],
    aiRole: { en: "Helps shortlist, checks submissions against the brief and drafts reports.", zh: "協助篩選、按簡報檢查提交內容及草擬報告。" },
    specialistRole: { en: "Creator managers negotiate, coordinate and resolve issues.", zh: "創作者經理負責洽談、協調及處理問題。" },
    reviewResponsibility: { en: "You approve creators and final content.", zh: "由你批准創作者人選及最終內容。" },
    included: { en: ["Agreed number of creators", "Review and reporting"], zh: ["議定數目的創作者", "審閱及報告"] },
    excluded: { en: ["Creator fees (unless agreed)", "Guaranteed reach"], zh: ["創作者費用（另有協議除外）", "保證觸及人數"] },
    thirdParty: { en: "Platform rules and disclosure requirements apply.", zh: "須遵守平台規則及披露要求。" },
    sample: { label: { en: "Sample content check", zh: "內容檢查示例" }, rows: { en: [["Mandatory", "Show lid lock"], ["Claim check", "No price mentioned"], ["Disclosure", "#ad present"], ["Status", "Returned: colour name wrong"]], zh: [["必要事項", "展示杯蓋鎖扣"], ["宣稱檢查", "沒有提及價錢"], ["披露", "已標示 #ad"], ["狀態", "已退回：顏色名稱錯誤"]] } },
    startingScope: { en: "One programme with up to 20 creators.", zh: "一個計劃，最多 20 位創作者。" },
    products: ["whatsapp-aigc", "social-listening"],
    industries: ["beauty-luxury", "food-beverage", "hospitality-travel"],
    members: ["adfocate", "kocmax", "50-add-oil"],
  },
  {
    id: "ecommerce-growth",
    headlineAccent: { en: "to checkout", zh: "到結帳" },
    objective: "convert",
    name: { en: "E-commerce Growth", zh: "電商增長" },
    eyebrow: { en: "Catalogue to checkout", zh: "由產品目錄到結帳" },
    summary: { en: "Catalogue content, customer journeys, conversion and measurement within agreed systems.", zh: "在議定系統內處理產品內容、顧客旅程、轉化及衡量。" },
    problem: { en: "Product pages are incomplete, journeys leak and nobody can say which fix matters most.", zh: "產品頁資料不全，顧客旅程流失，卻無人說得出哪項改善最重要。" },
    deliverables: { en: ["Catalogue content audit", "Product page improvements", "Journey and conversion fixes", "Commercial reporting"], zh: ["產品內容審核", "產品頁改善", "旅程及轉化修正", "商業報告"] },
    inputs: { en: ["Store platform access", "Product data", "Analytics", "Campaign calendar"], zh: ["網店平台存取權", "產品資料", "分析數據", "宣傳日程"] },
    process: [
      { ...p("Audit", "審核"), copy: { en: "Catalogue and journey gaps.", zh: "產品目錄及旅程缺口。" } },
      { ...p("Fix content", "修正內容"), copy: { en: "Structured product records and pages.", zh: "結構化產品紀錄及頁面。" } },
      { ...p("Improve journeys", "改善旅程"), copy: { en: "Test and refine.", zh: "測試及調整。" } },
      { ...p("Measure", "衡量"), copy: { en: "Commercial reporting.", zh: "商業報告。" } },
    ],
    aiRole: { en: "Validates product records and drafts page copy from fields (Website / CMS).", zh: "驗證產品紀錄，並根據欄位草擬頁面文字（Website / CMS）。" },
    specialistRole: { en: "E-commerce specialists prioritise and implement changes.", zh: "電商專家排列優先次序並執行改動。" },
    reviewResponsibility: { en: "Merchandising owners approve product content.", zh: "由商品負責人批准產品內容。" },
    included: { en: ["Agreed catalogue scope", "Reporting"], zh: ["議定的產品範圍", "報告"] },
    excluded: { en: ["Inventory, payment, refund and order operations", "Platform fees"], zh: ["庫存、付款、退款及訂單運作", "平台費用"] },
    thirdParty: { en: "Depends on your commerce platform’s capabilities.", zh: "視乎你的電商平台功能。" },
    sample: { label: { en: "Sample product record check", zh: "產品紀錄檢查示例" }, rows: { en: [["SKU", "BTL-750-HB (sample)"], ["Missing", "Care instructions"], ["Action", "Request from product team"], ["Page status", "Held until complete"]], zh: [["SKU", "BTL-750-HB（示例）"], ["缺漏", "保養說明"], ["行動", "向產品團隊索取"], ["頁面狀態", "資料齊全前暫緩上架"]] } },
    startingScope: { en: "One store, one category of up to 200 products.", zh: "一間網店、一個類別，最多 200 件產品。" },
    products: ["website-cms", "creativemax"],
    industries: ["retail-ecommerce", "beauty-luxury"],
    members: ["kinnso"],
  },
  {
    id: "digital-experience",
    headlineAccent: { en: "that convert", zh: "有助轉化" },
    objective: "convert",
    name: { en: "Digital Experience", zh: "數碼體驗" },
    eyebrow: { en: "Websites and journeys that convert", zh: "有助轉化的網站及顧客旅程" },
    summary: { en: "Websites, landing pages and journeys, designed and built with structured content and accessible interfaces.", zh: "網站、登陸頁及顧客旅程的設計與建立，採用結構化內容及無障礙介面。" },
    problem: { en: "The website says one thing, campaigns say another, and every page change waits for a developer. Visitors leave before they find the answer or the next step.", zh: "網站與宣傳內容各說各話，每次修改頁面都要等待開發人員；訪客未找到答案或下一步便已離開。" },
    deliverables: { en: ["Journey map and page structure", "Page and landing page designs", "Build on the agreed platform", "Content model for future updates", "Measurement plan and launch checks"], zh: ["顧客旅程圖及頁面結構", "頁面及登陸頁設計", "於議定平台上建立", "方便日後更新的內容模型", "成效衡量計劃及推出前檢查"] },
    inputs: { en: ["Business objective and audiences", "Brand guidelines and existing content", "Platform and hosting access", "Analytics access"], zh: ["業務目標及受眾", "品牌指引及現有內容", "平台及託管存取權", "分析工具存取權"] },
    process: [
      { ...p("Discover", "探索"), copy: { en: "Audiences, tasks and current journey gaps.", zh: "受眾、目標任務及現有旅程缺口。" } },
      { ...p("Design", "設計"), copy: { en: "Structure, content model and page designs.", zh: "結構、內容模型及頁面設計。" } },
      { ...p("Build", "建立"), copy: { en: "Accessible, measurable pages on the agreed platform.", zh: "在議定平台上建立無障礙、可衡量的頁面。" } },
      { ...p("Launch and improve", "推出及改善"), copy: { en: "Launch checks, measurement, then iteration.", zh: "推出前檢查、衡量，再持續優化。" } },
    ],
    aiRole: { en: "Drafts page copy from approved facts, checks content against the content model and flags missing fields (Website / CMS).", zh: "根據已確認資料草擬頁面文字，按內容模型檢查內容並標示缺漏欄位（Website / CMS）。" },
    specialistRole: { en: "UX designers, content designers and developers design, build and test the experience.", zh: "由用戶體驗設計師、內容設計師及開發人員負責設計、建立及測試。" },
    reviewResponsibility: { en: "You approve designs, content and the go-live decision.", zh: "由你批准設計、內容及正式推出的決定。" },
    included: { en: ["Agreed pages and templates", "Accessibility and performance checks before launch", "Handover and editor guidance"], zh: ["議定的頁面及範本", "推出前的無障礙及效能檢查", "移交及編輯指引"] },
    excluded: { en: ["Hosting, domain and licence fees", "Ongoing content production (scoped separately)", "Payment and order systems"], zh: ["託管、網域及授權費用", "持續內容製作（另行界定）", "付款及訂單系統"] },
    thirdParty: { en: "Hosting, CMS and plug-in providers' terms and limits apply.", zh: "須遵守託管、CMS 及外掛供應商的條款及限制。" },
    sample: { label: { en: "Sample page brief", zh: "頁面簡報示例" }, rows: { en: [["Page", "Service enquiry landing page (sample)"], ["Visitor task", "Understand the offer and send an enquiry"], ["Content needed", "Three approved facts, FAQ, contact form"], ["Measure", "Enquiry completion rate"]], zh: [["頁面", "服務查詢登陸頁（示例）"], ["訪客任務", "了解服務並提交查詢"], ["所需內容", "三項已確認資料、常見問題、聯絡表格"], ["衡量", "查詢完成率"]] } },
    startingScope: { en: "One landing page or one priority journey on your current platform.", zh: "在現有平台上建立一個登陸頁或一條重點顧客旅程。" },
    products: ["website-cms", "aiso"],
    industries: ["property-real-estate", "hospitality-travel", "b2b-professional-services"],
    members: [],
  },
  {
    id: "business-intelligence",
    headlineAccent: { en: "act on", zh: "據此行動" },
    objective: "understand",
    name: { en: "Business Intelligence", zh: "商業智能" },
    eyebrow: { en: "Reports people act on", zh: "團隊會據此行動的報告" },
    summary: { en: "Data definitions, dashboards, reporting cadence and decision briefs.", zh: "資料定義、儀表板、報告周期及決策簡報。" },
    problem: { en: "Every team counts differently and the monthly pack takes days to assemble.", zh: "各團隊計算方式不一，每月報告要花數日整理。" },
    deliverables: { en: ["Agreed metric definitions", "Dashboards", "Reporting cadence", "Written decision briefs"], zh: ["議定的指標定義", "儀表板", "報告周期", "書面決策簡報"] },
    inputs: { en: ["Data sources and access", "Business questions", "Existing reports"], zh: ["資料來源及存取權", "業務問題", "現有報告"] },
    process: [
      { ...p("Define", "定義"), copy: { en: "Metrics and owners.", zh: "指標及負責人。" } },
      { ...p("Connect", "連接"), copy: { en: "Sources and quality checks.", zh: "來源及質素檢查。" } },
      { ...p("Visualise", "視覺化"), copy: { en: "Dashboards people use.", zh: "團隊會用的儀表板。" } },
      { ...p("Brief", "簡報"), copy: { en: "What changed and why.", zh: "有何變化及原因。" } },
    ],
    aiRole: { en: "Drafts written commentary on changes for analyst review.", zh: "就數據變化草擬文字評述，供分析師審閱。" },
    specialistRole: { en: "Analysts define metrics, build dashboards and validate.", zh: "分析師定義指標、建立儀表板及驗證。" },
    reviewResponsibility: { en: "Analysts validate numbers; managers own conclusions.", zh: "分析師核實數字；結論由經理負責。" },
    included: { en: ["Agreed dashboards", "Documentation"], zh: ["議定的儀表板", "文件"] },
    excluded: { en: ["BI software licences", "Data we cannot legally access"], zh: ["BI 軟件授權", "我們無法合法取得的資料"] },
    thirdParty: { en: "Depends on source systems' export and API access.", zh: "視乎來源系統的匯出及介面存取。" },
    sample: { label: { en: "Sample decision brief line", zh: "決策簡報示例" }, rows: { en: [["Metric", "Enquiry response time"], ["Change", "Slower in week 3"], ["Likely cause", "Event backlog"], ["Decision needed", "Add weekend cover?"]], zh: [["指標", "查詢回應時間"], ["變化", "第三週較慢"], ["可能原因", "活動後積壓"], ["需要的決定", "是否增加週末人手？"]] } },
    startingScope: { en: "One management report rebuilt with agreed definitions.", zh: "以議定定義重建一份管理報告。" },
    products: ["social-listening"],
    industries: ["retail-ecommerce", "financial-services", "b2b-professional-services"],
    members: [],
    workstream: "strategy-roadmap",
  },
  {
    id: "data-hub",
    headlineAccent: { en: "every workflow", zh: "可依賴的資料" },
    objective: "scale",
    name: { en: "Data Hub & Integration", zh: "數據中樞與系統串接" },
    eyebrow: { en: "Trusted data for every workflow", zh: "每個流程都可依賴的資料" },
    summary: { en: "Source mapping, data quality, permitted identity/event handling and integration handover.", zh: "來源對照、資料質素、獲准的身份及事件處理，以及串接移交。" },
    problem: { en: "The same customer exists five times in five systems, and automation inherits the mess.", zh: "同一位顧客在五個系統中有五份紀錄，自動化流程亦承接了這些混亂。" },
    deliverables: { en: ["Source map", "Data model and quality rules", "Integration flows", "Handover documentation"], zh: ["來源地圖", "資料模型及質素規則", "串接流程", "移交文件"] },
    inputs: { en: ["System access", "Data owners", "Privacy and consent requirements"], zh: ["系統存取權", "資料負責人", "私隱及同意要求"] },
    process: [
      { ...p("Map sources", "對照來源"), copy: { en: "What exists and who owns it.", zh: "現有資料及負責人。" } },
      { ...p("Model", "建模"), copy: { en: "Shared definitions and rules.", zh: "共用定義及規則。" } },
      { ...p("Integrate", "串接"), copy: { en: "Build and test flows.", zh: "建立及測試流程。" } },
      { ...p("Hand over", "移交"), copy: { en: "Monitoring and documentation.", zh: "監察及文件。" } },
    ],
    aiRole: { en: "Helps detect duplicates and anomalies for review.", zh: "協助找出重複及異常資料供審閱。" },
    specialistRole: { en: "Data engineers design and build integrations.", zh: "資料工程師設計及建立串接。" },
    reviewResponsibility: { en: "Data owners approve access and identity rules.", zh: "由資料負責人批准存取及身份規則。" },
    included: { en: ["Agreed sources and flows", "Documentation"], zh: ["議定的來源及流程", "文件"] },
    excluded: { en: ["Processing without a lawful basis", "Hosting fees"], zh: ["沒有合法依據的處理", "託管費用"] },
    thirdParty: { en: "Depends on each system’s API limits and terms.", zh: "視乎各系統的介面限制及條款。" },
    sample: { label: { en: "Sample source map row", zh: "來源地圖示例" }, rows: { en: [["Source", "Online store orders"], ["Owner", "E-commerce manager"], ["Key", "Order ID + email (hashed)"], ["Consent", "Marketing opt-in field"]], zh: [["來源", "網店訂單"], ["負責人", "電商經理"], ["識別鍵", "訂單編號＋電郵（雜湊）"], ["同意", "推廣同意欄位"]] } },
    startingScope: { en: "Map and connect two sources for one workflow.", zh: "為一個流程對照並連接兩個來源。" },
    products: ["website-cms", "customer-ops"],
    industries: ["retail-ecommerce", "financial-services", "healthcare-wellness"],
    members: ["aip"],
  },
  {
    id: "content-creative",
    headlineAccent: { en: "brand control", zh: "品牌可掌控" },
    objective: "acquire",
    name: { en: "Content & Creative", zh: "內容與創意" },
    eyebrow: { en: "Creative with brand control", zh: "品牌可掌控的創意" },
    summary: { en: "Strategy, brand inputs, production, variants, review and delivery.", zh: "內容策略、品牌素材、製作、版本、審閱及交付。" },
    problem: { en: "The team needs more versions in more languages without losing the brand or the facts.", zh: "團隊需要以更多語言製作更多版本，同時不能偏離品牌或事實。" },
    deliverables: { en: ["Content strategy and calendar", "Copy and visual production", "Variants per channel and language", "Review workflow and delivery"], zh: ["內容策略及日程", "文案及視覺製作", "按渠道及語言的版本", "審閱流程及交付"] },
    inputs: { en: ["Brand guidelines", "Approved facts", "Campaign briefs"], zh: ["品牌指引", "已確認資料", "宣傳簡報"] },
    process: [
      { ...p("Strategy", "策略"), copy: { en: "Themes and calendar.", zh: "主題及日程。" } },
      { ...p("Produce", "製作"), copy: { en: "Copy, visuals, video.", zh: "文案、視覺、影片。" } },
      { ...p("Review", "審閱"), copy: { en: "Brand and fact checks.", zh: "品牌及事實檢查。" } },
      { ...p("Deliver", "交付"), copy: { en: "Organised, labelled assets.", zh: "整理妥當並已標示的素材。" } },
    ],
    aiRole: { en: "Prepares first drafts and variants (CreativeMax, WhatsApp AIGC).", zh: "準備初稿及不同版本（CreativeMax、WhatsApp AIGC）。" },
    specialistRole: { en: "Writers, designers and producers craft and refine.", zh: "文案、設計師及製作人員負責創作及修飾。" },
    reviewResponsibility: { en: "Your brand team approves final assets.", zh: "由你的品牌團隊批准最終素材。" },
    included: { en: ["Agreed volume and formats", "Two review rounds"], zh: ["議定的數量及格式", "兩輪審閱"] },
    excluded: { en: ["Stock or talent licences unless agreed", "Publishing"], zh: ["圖庫或演員授權（另有協議除外）", "發布"] },
    thirdParty: { en: "Licensed assets follow their licence terms.", zh: "授權素材須按其授權條款使用。" },
    sample: { label: { en: "Sample asset record", zh: "素材紀錄示例" }, rows: { en: [["Asset", "Launch caption — 繁中"], ["Source facts", "4 of 4 used"], ["Review", "Approved with edits"], ["Export", "Campaign pack v2 (sample)"]], zh: [["素材", "推出文案——繁中"], ["來源資料", "已使用 4 項中的 4 項"], ["審閱", "修改後批准"], ["匯出", "宣傳套件 v2（示例）"]] } },
    startingScope: { en: "One campaign’s content pack in two languages.", zh: "一次宣傳的雙語內容套件。" },
    products: ["creativemax", "whatsapp-aigc"],
    industries: ["beauty-luxury", "retail-ecommerce", "food-beverage"],
    members: ["adfocate", "eldage"],
  },
  {
    id: "customer-experience",
    headlineAccent: { en: "route well", zh: "分流得宜" },
    objective: "retain",
    name: { en: "Customer Experience", zh: "顧客體驗" },
    eyebrow: { en: "Service journeys that route well", zh: "分流得宜的服務旅程" },
    summary: { en: "Journey design, knowledge, service routing, escalation and experience measurement.", zh: "旅程設計、知識庫、服務分流、上報及體驗衡量。" },
    problem: { en: "Routine questions swamp the team, while complex cases wait too long for the right person.", zh: "例行問題淹沒團隊，複雜個案卻要等很久才轉到合適的人手上。" },
    deliverables: { en: ["Service journey map", "Approved answer library", "Routing and escalation rules", "Experience measures"], zh: ["服務旅程地圖", "已確認答案庫", "分流及上報規則", "體驗指標"] },
    inputs: { en: ["Enquiry history", "Service policies", "Team structure"], zh: ["查詢記錄", "服務政策", "團隊架構"] },
    process: [
      { ...p("Map", "描繪"), copy: { en: "Journeys and pain points.", zh: "旅程及痛點。" } },
      { ...p("Knowledge", "知識"), copy: { en: "Approved answers.", zh: "已確認答案。" } },
      { ...p("Route", "分流"), copy: { en: "Rules and escalation.", zh: "規則及上報。" } },
      { ...p("Measure", "衡量"), copy: { en: "Experience and recovery.", zh: "體驗及補救。" } },
    ],
    aiRole: { en: "Classifies enquiries and drafts responses from approved answers (Customer Ops).", zh: "分類查詢並根據已確認答案草擬回覆（Customer Ops）。" },
    specialistRole: { en: "CX consultants design journeys and knowledge.", zh: "顧客體驗顧問設計旅程及知識庫。" },
    reviewResponsibility: { en: "Service leads own policy, sensitive cases and recovery.", zh: "服務主管負責政策、敏感個案及補救。" },
    included: { en: ["Agreed journeys and channels", "Training"], zh: ["議定的旅程及渠道", "培訓"] },
    excluded: { en: ["Staffing your service desk", "Automated replies on human-only categories"], zh: ["為你的客服部提供人手", "在只限專人處理的類別自動回覆"] },
    thirdParty: { en: "Depends on your helpdesk and messaging tools.", zh: "視乎你的客服及訊息工具。" },
    sample: { label: { en: "Sample routing decision", zh: "分流決定示例" }, rows: { en: [["Enquiry", "Warranty claim"], ["Category", "Human-only"], ["Owner", "Service team"], ["Draft", "None — routed directly"]], zh: [["查詢", "保養申索"], ["類別", "只限專人處理"], ["負責人", "客戶服務團隊"], ["草稿", "不設——直接轉交"]] } },
    startingScope: { en: "One service journey on one channel.", zh: "一個渠道上的一條服務旅程。" },
    products: ["customer-ops"],
    industries: ["healthcare-wellness", "hospitality-travel", "financial-services"],
    members: [],
    workstream: "workflow-agent-design",
  },
  {
    id: "workflow-automation",
    headlineAccent: { en: "redesigned", zh: "重新設計" },
    objective: "automate",
    name: { en: "Workflow Automation", zh: "工作流程自動化" },
    eyebrow: { en: "Repeated work, redesigned", zh: "重新設計重複工作" },
    summary: { en: "Process mapping, human decisions, system actions, exceptions and operating ownership.", zh: "流程描繪、人手決策、系統行動、例外處理及營運責任。" },
    problem: { en: "Work moves by email and copy-paste; exceptions disappear; no one can see the queue.", zh: "工作靠電郵和複製貼上推進；例外情況無聲無息地消失；無人看得見工作隊列。" },
    deliverables: { en: ["Process map", "Automated steps with approvals", "Exception queue", "Operating playbook"], zh: ["流程地圖", "附批核的自動化步驟", "例外處理隊列", "營運手冊"] },
    inputs: { en: ["Process owner", "Real examples", "System access", "Approval thresholds"], zh: ["流程負責人", "真實例子", "系統存取權", "批核門檻"] },
    process: [
      { ...p("Map", "描繪"), copy: { en: "Current steps and handoffs.", zh: "現行步驟及交接。" } },
      { ...p("Design", "設計"), copy: { en: "Human, AI and system roles.", zh: "人員、AI 及系統角色。" } },
      { ...p("Build", "建置"), copy: { en: "Configure and test.", zh: "設定及測試。" } },
      { ...p("Operate", "營運"), copy: { en: "Owners, measures, improvements.", zh: "負責人、指標、改善。" } },
    ],
    aiRole: { en: "Prepares, classifies and validates within defined steps.", zh: "在既定步驟內準備、分類及驗證。" },
    specialistRole: { en: "Automation specialists design and build.", zh: "自動化專家負責設計及建置。" },
    reviewResponsibility: { en: "Process owners approve material actions and exceptions.", zh: "流程負責人批准重大行動及例外。" },
    included: { en: ["One agreed workflow", "Testing and handover"], zh: ["一個議定的流程", "測試及移交"] },
    excluded: { en: ["Actions outside the agreed permissions", "Unsupported systems"], zh: ["超出議定權限的行動", "不支援的系統"] },
    thirdParty: { en: "Depends on connected systems' APIs.", zh: "視乎已串接系統的介面。" },
    sample: { label: { en: "Sample exception record", zh: "例外紀錄示例" }, rows: { en: [["Step", "Validate listing"], ["Exception", "Floor area missing"], ["Route", "Listing coordinator"], ["Status", "Waiting for input"]], zh: [["步驟", "驗證物業資料"], ["例外", "欠缺實用面積"], ["轉交", "物業資料統籌"], ["狀態", "等待補交"]] } },
    startingScope: { en: "One workflow with one exception queue.", zh: "一個流程及一條例外處理隊列。" },
    products: ["website-cms", "customer-ops"],
    industries: ["property-real-estate", "b2b-professional-services", "healthcare-wellness"],
    members: ["aip"],
    workstream: "workflow-agent-design",
  },
  {
    id: "whatsapp-automation",
    headlineAccent: { en: "with control", zh: "可控" },
    objective: "retain",
    name: { en: "WhatsApp Automation", zh: "WhatsApp 自動化" },
    eyebrow: { en: "Messaging journeys with control", zh: "可控的訊息旅程" },
    summary: { en: "Messaging, enquiry and notification journeys on WhatsApp Business.", zh: "在 WhatsApp Business 上設計訊息、查詢及通知旅程。" },
    problem: { en: "Customers message on WhatsApp but replies depend on who has the phone.", zh: "顧客透過 WhatsApp 查詢，回覆卻取決於誰拿着電話。" },
    deliverables: { en: ["Conversation and notification flows", "Approved templates", "Routing to people", "Conversation reporting"], zh: ["對話及通知流程", "已批准的訊息範本", "轉交專人的分流", "對話報告"] },
    inputs: { en: ["WhatsApp Business account via an approved provider", "Consent records", "Answer library", "Team owners"], zh: ["透過認可供應商開設的 WhatsApp Business 帳戶", "同意紀錄", "答案庫", "團隊負責人"] },
    process: [
      { ...p("Design flows", "設計流程"), copy: { en: "Enquiry and notification paths.", zh: "查詢及通知路徑。" } },
      { ...p("Templates", "範本"), copy: { en: "Approved message templates.", zh: "已批准的訊息範本。" } },
      { ...p("Route", "分流"), copy: { en: "Hand to people when needed.", zh: "需要時轉交專人。" } },
      { ...p("Report", "報告"), copy: { en: "Volumes, response, outcomes.", zh: "數量、回應、結果。" } },
    ],
    aiRole: { en: "Classifies incoming messages and drafts replies from approved answers.", zh: "分類傳入訊息，並根據已確認答案草擬回覆。" },
    specialistRole: { en: "Messaging specialists design flows and configure the provider.", zh: "訊息專家設計流程及設定供應商平台。" },
    reviewResponsibility: { en: "You approve templates, consent rules and human-only categories.", zh: "由你批准範本、同意規則及只限專人處理的類別。" },
    included: { en: ["Agreed flows", "Configuration and testing"], zh: ["議定的流程", "設定及測試"] },
    excluded: { en: ["Messaging fees", "Messages to contacts without opt-in"], zh: ["訊息費用", "向未同意的聯絡人發訊息"] },
    thirdParty: { en: "Meta’s WhatsApp Business policies and provider terms apply.", zh: "須遵守 Meta 的 WhatsApp Business 政策及供應商條款。" },
    sample: { label: { en: "Sample flow step", zh: "流程步驟示例" }, rows: { en: [["Message", "Is the Causeway Bay store open Sunday?"], ["Intent", "Store hours"], ["Draft", "From approved store-hours answer"], ["Send", "Only after agent approval (configured)"]], zh: [["訊息", "銅鑼灣門市星期日有開嗎？"], ["意圖", "門市營業時間"], ["草稿", "取自已確認的營業時間答案"], ["發送", "只在客服批准後（已設定）"]] } },
    startingScope: { en: "One enquiry flow and one notification type.", zh: "一條查詢流程及一種通知。" },
    products: ["customer-ops"],
    industries: ["property-real-estate", "food-beverage", "healthcare-wellness"],
    members: [],
  },
  {
    id: "ai-training",
    headlineAccent: { en: "run AI work", zh: "駕馭 AI 工作" },
    objective: "scale",
    name: { en: "AI Training & Enablement", zh: "AI 培訓與能力建立" },
    eyebrow: { en: "Teams ready to run AI work", zh: "讓團隊能駕馭 AI 工作" },
    summary: { en: "Audience, learning objectives, format, practical outputs and adoption support.", zh: "按對象設計學習目標、形式、實用成果及推行支援。" },
    problem: { en: "People were given AI tools but not the judgement, rules or practice to use them well.", zh: "員工拿到 AI 工具，卻未有足夠的判斷力、規則或練習去善用它們。" },
    deliverables: { en: ["Training plan by role", "Hands-on workshops", "Workflow prototypes", "Guidelines and adoption plan"], zh: ["按角色的培訓計劃", "實務工作坊", "流程原型", "指引及推行計劃"] },
    inputs: { en: ["Roles and teams", "Priority workflows", "Current policies"], zh: ["角色及團隊", "重點流程", "現行政策"] },
    process: [
      { ...p("Assess", "評估"), copy: { en: "Roles and skill gaps.", zh: "角色及技能缺口。" } },
      { ...p("Design", "設計"), copy: { en: "Objectives and format.", zh: "目標及形式。" } },
      { ...p("Deliver", "推行"), copy: { en: "Workshops on real work.", zh: "以實際工作為本的工作坊。" } },
      { ...p("Support", "支援"), copy: { en: "Follow-up and adoption.", zh: "跟進及推行。" } },
    ],
    aiRole: { en: "Used live in exercises; participants learn to review its output.", zh: "在練習中即場使用，學員學習如何審閱其輸出。" },
    specialistRole: { en: "FIMMICK trainers design and facilitate.", zh: "FIMMICK 導師負責設計及主持。" },
    reviewResponsibility: { en: "Managers confirm readiness and ongoing practice.", zh: "經理確認團隊是否準備就緒並持續實踐。" },
    included: { en: ["Agreed sessions", "Materials"], zh: ["議定的課節", "教材"] },
    excluded: { en: ["Tool licences", "Accredited certification"], zh: ["工具授權", "認可資歷證書"] },
    thirdParty: { en: "Exercises use tools you are licensed to use.", zh: "練習會使用你已獲授權的工具。" },
    sample: { label: { en: "Sample learning objective", zh: "學習目標示例" }, rows: { en: [["Audience", "Brand reviewers"], ["Objective", "Check AI drafts against approved facts"], ["Practice", "Review 5 sample drafts"], ["Output", "Personal review checklist"]], zh: [["對象", "品牌審閱人"], ["目標", "按已確認資料檢查 AI 草稿"], ["練習", "審閱 5 份示例草稿"], ["成果", "個人審閱清單"]] } },
    startingScope: { en: "A half-day workshop for one team.", zh: "為一個團隊舉辦半日工作坊。" },
    products: [],
    industries: ["b2b-professional-services", "financial-services", "healthcare-wellness"],
    members: [],
    workstream: "governance-adoption",
  },
];

export const serviceById = (id: ServiceId) => services.find((s) => s.id === id)!;
