import type { L } from "@/lib/i18n";

/** Shared interface strings. Keep keys stable; both locales are required. */
export const ui = {
  skip: { en: "Skip to main content", zh: "跳至主要內容" },
  menu: { en: "Menu", zh: "選單" },
  closeMenu: { en: "Close menu", zh: "關閉選單" },
  requestDemo: { en: "Request a Demo", zh: "預約產品示範" },
  exploreSolutions: { en: "Explore Solutions", zh: "查看業務解決方案" },
  discussConfiguration: { en: "Discuss Configuration", zh: "討論配置方案" },
  discussScope: { en: "Discuss a starting scope", zh: "討論起步範圍" },
  login: { en: "AIP login", zh: "AIP 登入" },
  language: { en: "Language", zh: "語言" },
  overview: { en: "Overview", zh: "概覽" },
  learnMore: { en: "Learn more", zh: "了解更多" },
  viewAll: { en: "View all", zh: "查看全部" },
  home: { en: "Home", zh: "首頁" },
  breadcrumb: { en: "Breadcrumb", zh: "導覽路徑" },
  primaryNav: { en: "Primary", zh: "主要導覽" },
  footerNav: { en: "Footer", zh: "頁尾導覽" },
  relatedProducts: { en: "Related products", zh: "相關產品" },
  relatedServices: { en: "Related services", zh: "相關服務" },
  relatedIndustries: { en: "Relevant industries", zh: "相關行業" },
  relatedCases: { en: "Related case studies", zh: "相關案例" },
  relatedResources: { en: "Related resources", zh: "相關資源" },
  relatedEcosystem: { en: "Ecosystem connection", zh: "生態系統連繫" },
  startingScope: { en: "Starting scope", zh: "起步範圍" },
  inputs: { en: "What you provide", zh: "你需要提供" },
  outputs: { en: "What you receive", zh: "你會得到" },
  humanDecision: { en: "Where people decide", zh: "由人決定的環節" },
  faqs: { en: "Questions", zh: "常見問題" },
  availability: { en: "Availability", zh: "供應狀況" },
  exampleMode: { en: "Example mode", zh: "示例性質" },
  availabilityDiscuss: { en: "Configured per engagement — availability confirmed when we scope your workflow", zh: "按項目配置——於界定流程範圍時確認供應安排" },
  availabilityAvailable: { en: "Available", zh: "現已提供" },
  availabilityConfigured: { en: "Available as a configured workflow", zh: "以已配置流程形式提供" },
  modeSample: { en: "Illustrative example — sample data", zh: "流程示範・示例資料" },
  modeRecorded: { en: "Recorded demonstration", zh: "錄製示範" },
  modeLive: { en: "Live product", zh: "實際產品" },
  reset: { en: "Reset example", zh: "重設示例" },
  footerTagline: { en: "Agentic AI Platform & Business Solutions, built in Hong Kong since 2008.", zh: "企業 AI 智能體平台與業務解決方案，2008 年起植根香港。" },
  rights: { en: "All rights reserved.", zh: "版權所有。" },
  privacy: { en: "Privacy", zh: "私隱政策" },
  terms: { en: "Terms", zh: "條款" },
  cookies: { en: "Cookies", zh: "Cookie 政策" },
  notFoundTitle: { en: "We couldn't find that page", zh: "找不到此頁面" },
  notFoundBody: { en: "The page may have moved. Try one of these starting points.", zh: "頁面可能已移動，請從以下位置繼續瀏覽。" },
  archiveNotice: { en: "Archive article", zh: "文章存檔" },
  published: { en: "Published", zh: "發布日期" },
  updated: { en: "Updated", zh: "更新日期" },
  readTime: { en: "Reading time", zh: "閱讀時間" },
  originalLanguage: { en: "Original language", zh: "原文語言" },
  search: { en: "Search", zh: "搜尋" },
  clearFilters: { en: "Clear filters", zh: "清除篩選" },
  all: { en: "All", zh: "全部" },
  results: { en: "results", zh: "項結果" },
  noResults: { en: "Nothing matches these filters yet.", zh: "暫時沒有符合篩選條件的內容。" },
  previous: { en: "Previous", zh: "上一頁" },
  next: { en: "Next", zh: "下一頁" },
  page: { en: "Page", zh: "頁" },
  download: { en: "Download", zh: "下載" },
  watch: { en: "Watch", zh: "觀看" },
  transcript: { en: "Transcript", zh: "文字稿" },
  backTo: { en: "Back to", zh: "返回" },
  sampleLabel: { en: "Sample", zh: "示例" },
  step: { en: "Step", zh: "步驟" },
} satisfies Record<string, L>;

export type UiKey = keyof typeof ui;
