import Link from "next/link";
import type { ReactNode } from "react";
import { href, t, type L, type Locale } from "@/lib/i18n";
import { paths } from "@/lib/routes";
import { ui } from "@/content/ui";
import { products, productById } from "@/content/products";
import { services, serviceById } from "@/content/services";
import { industries, industryById } from "@/content/industries";
import { cases, caseKindLabel } from "@/content/cases";
import { members, memberGroups, ecosystemBoundary } from "@/content/ecosystem";
import { platformLayers, sampleScenario } from "@/content/platform";
import { programme, programmeNote, sampleHeatmap, heatmapColumns, workstreamById } from "@/content/transformation";
import { solutionById } from "@/content/solutions";
import * as ex from "@/content/examples";
import type { CaseStudy, ExampleId, IndustryId, ProductId, ServiceId } from "@/content/types";
import { PlatformLayers } from "./diagrams/PlatformLayers";
import { BeforeAfter, type BaStep } from "./diagrams/BeforeAfter";
import { IndustryMap, type IndustryView } from "./diagrams/IndustryMap";
import { Roadmap } from "./diagrams/Roadmap";
import { EcosystemMap } from "./diagrams/EcosystemMap";
import { ExampleViewer, SingleExample, type ExampleBundle } from "./examples/ExampleViewer";
import type { ExampleChrome } from "./examples/Examples";
import { CtaBand, LinkButton } from "./ui";

const tr = <T,>(value: L<T>, locale: Locale) => t(value, locale);

/* ---------------------------------------------------------------- examples */

function chrome(locale: Locale, id: ExampleId, productId: ProductId, contactLabel?: L): ExampleChrome {
  const meta = ex.exampleMeta[id];
  const en = locale === "en";
  return {
    title: tr(meta.title, locale),
    lead: tr(meta.lead, locale),
    notice: tr(ex.sampleNotice, locale),
    reset: tr(ui.reset, locale),
    panes: en ? { input: "Input", work: "Prepared work", review: "Human review", output: "Output" } : { input: "輸入", work: "準備好的工作", review: "人手審閱", output: "輸出" },
    footnote: en
      ? "Runs entirely in your browser with fixed sample data. Nothing is sent, published, synced or generated by AI in this example."
      : "此示例只在你的瀏覽器內以固定示例資料運行，不會發送、發布、同步任何內容，亦不涉及實際 AI 生成。",
    productCta: { label: `${en ? "See" : "了解"} ${productById(productId).name}`, href: href(locale, paths.product(productId)) },
    contactCta: { label: tr(contactLabel ?? ui.discussConfiguration, locale), href: href(locale, paths.contact({ intent: "configuration", product: productId, example: id })) },
  };
}

export function exampleData<K extends ExampleId>(locale: Locale, id: K): ExampleBundle[K] {
  const en = locale === "en";
  const toneLabel = (tone: string) => (en ? { positive: "Positive", negative: "Negative", mixed: "Mixed / question" } : { positive: "正面", negative: "負面", mixed: "中性／提問" })[tone as "positive"] ?? tone;
  const builders: { [P in ExampleId]: () => ExampleBundle[P] } = {
    intelligence: () => ({
      chrome: chrome(locale, "intelligence", "social-listening"),
      topics: ex.intelTopics.map((x) => ({ id: x.id, label: tr(x.label, locale) })),
      sources: ex.intelSources.map((x) => ({ id: x.id, label: tr(x.label, locale) })),
      evidence: ex.intelEvidence.map((e) => ({ ...e, text: tr(e.text, locale), toneLabel: toneLabel(e.tone) })),
      interpretation: Object.fromEntries(Object.entries(ex.intelInterpretation).map(([k, v]) => [k, { summary: tr(v.summary, locale), priorities: v.priorities.map((p) => tr(p, locale)) }])),
      aiso: ex.aisoChecks.map((c) => ({ ...c, question: tr(c.question, locale), note: tr(c.note, locale) })),
      s: en
        ? { topic: "Topic", dataset: "Dataset", listening: "Social listening", aiSearch: "AI-search check (AISO)", source: "Source category", allSources: "All sources", evidence: "Linked evidence", none: "No sample evidence for this source.", interpretation: "Draft interpretation", priorities: "Prioritised actions", analyst: "Analyst review", markReviewed: "Mark priorities reviewed", reviewed: "Reviewed by analyst (sample)", notReviewed: "Awaiting analyst review", mentioned: "Brand mentioned", notMentioned: "Brand not mentioned", separate: "Listening and AI-search evidence are separate datasets and are never combined into one score." }
        : { topic: "話題", dataset: "資料組合", listening: "社交聆聽", aiSearch: "AI 搜尋檢查（AISO）", source: "來源類別", allSources: "全部來源", evidence: "已連結證據", none: "此來源沒有示例證據。", interpretation: "解讀草稿", priorities: "優先行動", analyst: "分析師審閱", markReviewed: "標記優先次序已審閱", reviewed: "分析師已審閱（示例）", notReviewed: "等待分析師審閱", mentioned: "有提及品牌", notMentioned: "未有提及品牌", separate: "社交聆聽與 AI 搜尋證據屬不同資料組合，不會合併成單一分數。" },
    }),
    content: () => ({
      chrome: chrome(locale, "content", "creativemax"),
      facts: tr(ex.contentFacts, locale),
      scenarios: ex.contentScenarios.map((s) => ({ id: s.id, label: tr(s.label, locale), extraFacts: tr(s.extraFacts, locale), formats: s.formats.map((f) => ({ id: f.id, label: tr(f.label, locale), draft: tr(f.draft, locale) })) })),
      s: en
        ? { scenario: "Scenario", format: "Format", facts: "Approved source facts", draft: "Editable draft", editHint: "Edit freely. Editing a reviewed draft sends it back for review.", markReviewed: "Mark sample reviewed", statusDraft: "Draft — not reviewed", statusReviewed: "Reviewed (sample)", statusChanged: "Changed since review — review again", priceCheckOk: "No price mentioned (none supplied)", priceCheckWarn: "Mentions a price — not in the approved facts", factsLinked: "Draft uses only the listed facts", exportLabel: "Export sample file", exportDisabled: "Export is available once the current draft is reviewed.", exported: "Sample file downloaded (.txt).", fileHeader: "ILLUSTRATIVE SAMPLE — FIMMICK content workflow example. Sample data only; not a real campaign or approval.", reviewer: "Reviewer: Brand manager (sample role)" }
        : { scenario: "情境", format: "格式", facts: "已確認來源資料", draft: "可編輯草稿", editHint: "可自由修改；已審閱的草稿一經修改，便需重新審閱。", markReviewed: "標記示例為已審閱", statusDraft: "草稿——未審閱", statusReviewed: "已審閱（示例）", statusChanged: "審閱後曾修改——請重新審閱", priceCheckOk: "沒有提及價錢（未有提供）", priceCheckWarn: "提及價錢——不在已確認資料之內", factsLinked: "草稿只使用所列資料", exportLabel: "匯出示例檔案", exportDisabled: "目前草稿審閱後即可匯出。", exported: "已下載示例檔案（.txt）。", fileHeader: "示例檔案 —— FIMMICK 內容流程示範，只含示例資料，並非真實宣傳或批核。", reviewer: "審閱人：品牌經理（示例角色）" },
    }),
    "follow-up": () => ({
      chrome: chrome(locale, "follow-up", "customer-ops"),
      enquiries: ex.enquiries.map((e) => ({ ...e, channel: tr(e.channel, locale), message: tr(e.message, locale), intent: tr(e.intent, locale), priority: tr(e.priority, locale), drafts: Object.fromEntries(Object.entries(e.drafts).map(([k, v]) => [k, v ? tr(v, locale) : null])) })),
      owners: ex.owners.map((o) => ({ id: o.id, label: tr(o.label, locale) })),
      actions: ex.nextActions.map((a) => ({ id: a.id, label: tr(a.label, locale) })),
      s: en
        ? { enquiry: "Sample enquiry", record: "Record", channel: "Channel", received: "Received", intent: "Intent", priority: "Priority", owner: "Owner", action: "Next action", suggested: "suggested", draft: "Proposed response", noDraft: "No draft — this category goes straight to a person.", humanOnly: "Human-only category", approve: "Owner approves task", statusOpen: "Open — awaiting owner", statusApproved: "Approved by owner (sample)", notSent: "Nothing is sent in this example. Sending needs a configured channel and your approval rules.", task: "Next task", due: "Follow-up by" }
        : { enquiry: "示例查詢", record: "紀錄", channel: "渠道", received: "收到時間", intent: "意圖", priority: "優先次序", owner: "負責人", action: "下一步行動", suggested: "建議", draft: "建議回覆", noDraft: "不設草稿——此類別直接交由專人處理。", humanOnly: "只限專人處理", approve: "負責人批准工作", statusOpen: "待處理——等待負責人", statusApproved: "負責人已批准（示例）", notSent: "此示例不會發送任何內容；發送需要已設定的渠道及你的批核規則。", task: "下一步工作", due: "跟進期限" },
    }),
    "website-ops": () => ({
      chrome: chrome(locale, "website-ops", "website-cms"),
      changes: ex.recordChanges.map((c) => ({ id: c.id, label: tr(c.label, locale), record: c.record, variant: c.id === "new-colour" ? "stone" : c.id === "missing-field" ? "lime" : "blue", fields: c.fields.map((f) => ({ name: tr(f.name, locale), before: tr(f.before, locale), after: tr(f.after, locale), changed: f.changed, valid: f.valid, note: f.note ? tr(f.note, locale) : undefined })), preview: { title: tr(c.preview.title, locale), lines: c.preview.lines.map((l) => tr(l, locale)) } })),
      s: en
        ? { change: "Record change", record: "Record", field: "Field", before: "Before", after: "After", validation: "Validation", valid: "all required fields present", invalid: "required field missing — held", approve: "Approve change", returnLabel: "Return", statusPending: "Awaiting review", statusApproved: "Approved — preview updated (sample)", statusReturned: "Returned to editor", statusHeld: "Held until the missing field is supplied", preview: "Page preview · sample", previewNote: "Preview only. Nothing is published in this example.", history: "Change history", historyCreated: "change drafted from record", historyApproved: "approved by content owner (sample)", historyReturned: "returned by content owner (sample)" }
        : { change: "紀錄變更", record: "紀錄", field: "欄位", before: "更新前", after: "更新後", validation: "驗證", valid: "必填欄位齊全", invalid: "欠缺必填欄位——暫緩", approve: "批准變更", returnLabel: "退回", statusPending: "等待審閱", statusApproved: "已批准——預覽已更新（示例）", statusReturned: "已退回編輯", statusHeld: "補交缺漏欄位前暫緩", preview: "頁面預覽・示例", previewNote: "只供預覽，此示例不會發布任何內容。", history: "變更記錄", historyCreated: "根據紀錄草擬變更", historyApproved: "內容負責人已批准（示例）", historyReturned: "內容負責人已退回（示例）" },
    }),
  };
  return builders[id]() as ExampleBundle[K];
}

export function ExampleTabs({ locale, initial = "content" }: { locale: Locale; initial?: ExampleId }) {
  const bundle: ExampleBundle = {
    intelligence: exampleData(locale, "intelligence"),
    content: exampleData(locale, "content"),
    "follow-up": exampleData(locale, "follow-up"),
    "website-ops": exampleData(locale, "website-ops"),
  };
  const tabs = (["intelligence", "content", "follow-up", "website-ops"] as const).map((id) => ({
    id,
    label: tr(solutionById(ex.exampleMeta[id].solution).short, locale),
    hint: ex.exampleMeta[id].products.map((p) => productById(p).name).join(" · "),
  }));
  return <ExampleViewer bundle={bundle} tabs={tabs} initial={initial} label={locale === "en" ? "Choose an example" : "選擇示例"} />;
}

export function ExampleBlock({ locale, id }: { locale: Locale; id: ExampleId }) {
  switch (id) {
    case "intelligence":
      return <SingleExample id="intelligence" data={exampleData(locale, "intelligence")} />;
    case "content":
      return <SingleExample id="content" data={exampleData(locale, "content")} />;
    case "follow-up":
      return <SingleExample id="follow-up" data={exampleData(locale, "follow-up")} />;
    default:
      return <SingleExample id="website-ops" data={exampleData(locale, "website-ops")} />;
  }
}

/* ---------------------------------------------------------------- diagrams */

export function PlatformLayersBlock({ locale, variant = "dark" }: { locale: Locale; variant?: "dark" | "light" }) {
  const en = locale === "en";
  return (
    <PlatformLayers
      variant={variant}
      layers={platformLayers.map((l) => ({ id: l.id, number: l.number, name: tr(l.name, locale), question: tr(l.question, locale), explanation: tr(l.explanation, locale), shows: tr(l.shows, locale), scenarioLabel: tr(l.scenario.label, locale), scenarioItems: tr(l.scenario.items, locale) }))}
      steps={sampleScenario.steps.map((s) => tr(s, locale))}
      labels={en ? { shows: "What this layer shows", scenario: "In the sample", select: "Platform layers", journey: "Sample scenario steps" } : { shows: "此層展示", scenario: "示例中", select: "平台層", journey: "示例情境步驟" }}
    />
  );
}

export function BeforeAfterBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  const before: BaStep[] = en
    ? [
        { title: "Brief arrives by email", copy: "Facts sit in an attachment and a chat thread.", kind: "manual", tag: "Manual" },
        { title: "Copy written from memory", copy: "Claims are retyped; colour names drift.", kind: "pain", tag: "Risk" },
        { title: "Approval in chat", copy: "“Looks good” in a group chat; no record of what was approved.", kind: "pain", tag: "Risk" },
        { title: "Re-edits after approval", copy: "Changes made after sign-off go unnoticed.", kind: "pain", tag: "Risk" },
        { title: "Files emailed around", copy: "Final version unclear; nothing reusable next time.", kind: "manual", tag: "Manual" },
      ]
    : [
        { title: "以電郵收到簡報", copy: "資料散落在附件及聊天記錄中。", kind: "manual", tag: "人手" },
        { title: "憑記憶撰寫文案", copy: "宣稱重新打字；顏色名稱出錯。", kind: "pain", tag: "風險" },
        { title: "在聊天中批核", copy: "群組中一句「好」，卻沒有記錄批准了甚麼。", kind: "pain", tag: "風險" },
        { title: "批准後再修改", copy: "確認後的改動無人察覺。", kind: "pain", tag: "風險" },
        { title: "以電郵傳送檔案", copy: "最終版本不清，下次無法重用。", kind: "manual", tag: "人手" },
      ];
  const after: BaStep[] = en
    ? [
        { title: "Approved facts as the source", copy: "The brief links to one list of approved facts.", kind: "system", tag: "Data" },
        { title: "Drafts prepared from the facts", copy: "Variants show which facts they used.", kind: "ai", tag: "AI prepares" },
        { title: "Named reviewer decides", copy: "Approve, edit or return — each decision is recorded.", kind: "human", tag: "People decide" },
        { title: "Edits reset approval", copy: "Changing an approved draft sends it back for review.", kind: "human", tag: "Control" },
        { title: "Export with record", copy: "Selected items leave with sources and review notes.", kind: "system", tag: "Record" },
      ]
    : [
        { title: "以已確認資料作來源", copy: "簡報連結到一份已確認資料清單。", kind: "system", tag: "資料" },
        { title: "根據資料準備草稿", copy: "每個版本都列明所用資料。", kind: "ai", tag: "AI 準備" },
        { title: "由指定審閱人決定", copy: "批准、修改或退回，每個決定都有記錄。", kind: "human", tag: "由人決定" },
        { title: "修改即需重新批核", copy: "已批准的草稿一經修改便退回審閱。", kind: "human", tag: "管控" },
        { title: "連記錄一併匯出", copy: "選定內容連同來源及審閱意見輸出。", kind: "system", tag: "記錄" },
      ];
  return (
    <BeforeAfter
      before={before}
      after={after}
      labels={en ? { before: "Before: manual handoffs", after: "After: reviewed workflow", group: "Compare workflows", note: "Process comparison only. No time or cost savings are claimed; results depend on your workflow and are measured after a first deployment." } : { before: "之前：人手交接", after: "之後：經審閱的流程", group: "比較流程", note: "此為流程比較，並不聲稱節省任何時間或成本；實際成效視乎你的流程，並於首次部署後量度。" }}
    />
  );
}

export function IndustryMapBlock({ locale, ids }: { locale: Locale; ids?: IndustryId[] }) {
  const en = locale === "en";
  const list = ids ? ids.map(industryById) : industries;
  const views: IndustryView[] = list.map((i) => {
    const evidenceCase = cases.find((c) => c.industries.includes(i.id) && c.kind === "client-work");
    return {
      id: i.id,
      name: tr(i.name, locale),
      short: i.products.map((p) => productById(p).name).join(" · "),
      problem: tr(i.problem, locale),
      journey: i.journey.map((j) => ({ step: tr(j.step, locale), copy: tr(j.copy, locale), human: !!j.human, who: j.human ? (en ? "Your team decides" : "由你的團隊決定") : j.product ? productById(j.product).name : "" })),
      products: i.products.map((p) => ({ label: productById(p).name, href: href(locale, paths.product(p)) })),
      services: i.services.map((s) => ({ label: tr(serviceById(s).name, locale), href: href(locale, paths.service(s)) })),
      evidence: evidenceCase ? { label: tr(evidenceCase.title, locale), href: href(locale, paths.case(evidenceCase.slug)), kind: tr(caseKindLabel[evidenceCase.kind], locale) } : undefined,
      proof: tr(i.proof, locale),
      output: tr(i.output, locale),
      cta: { label: en ? `Discuss ${tr(i.name, locale)}` : `討論${tr(i.name, locale)}方案`, href: href(locale, paths.contact({ intent: "configuration", industry: i.id })) },
      detail: { label: en ? "Full industry page" : "查看完整行業頁面", href: href(locale, paths.industry(i.id)) },
    };
  });
  return <IndustryMap industries={views} labels={en ? { group: "Choose a sector", products: "Products", services: "Services", evidence: "Evidence", output: "Output", noEvidence: "No published case for this sector yet — the workflow shown is a labelled example." } : { group: "選擇行業", products: "產品", services: "服務", evidence: "證據", output: "成果", noEvidence: "此行業暫未有公開案例——所示流程為已標示的示例。" }} />;
}

export function IndustryMatrix({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <div className="table-wrap">
      <table className="data matrix">
        <caption className="sr-only">{en ? "Which products each industry page applies" : "各行業應用的產品"}</caption>
        <thead>
          <tr>
            <th scope="col">{en ? "Industry" : "行業"}</th>
            {products.map((p) => (
              <th scope="col" key={p.id}>
                {p.name}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {industries.map((i) => (
            <tr key={i.id}>
              <th scope="row">
                <Link href={href(locale, paths.industry(i.id))}>{tr(i.name, locale)}</Link>
              </th>
              {products.map((p) =>
                i.products.includes(p.id) ? (
                  <td key={p.id} className="on">
                    <span aria-hidden="true" />
                    <span className="sr-only">{en ? "Applied" : "適用"}</span>
                  </td>
                ) : (
                  <td key={p.id} className="off" aria-label={en ? "Not applied" : "不適用"}>
                    –
                  </td>
                ),
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function RoadmapBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <Roadmap
      steps={programme.map((p) => ({
        id: p.id,
        number: p.number,
        name: tr(p.name, locale),
        decision: tr(p.decision, locale),
        inputs: tr(p.inputs, locale),
        deliverable: tr(p.deliverable, locale),
        humanRole: tr(p.humanRole, locale),
        link: p.workstream
          ? { label: tr(workstreamById(p.workstream).name, locale), href: href(locale, paths.workstream(p.workstream)) }
          : p.service
            ? { label: tr(serviceById(p.service).name, locale), href: href(locale, paths.service(p.service)) }
            : undefined,
      }))}
      labels={en ? { group: "Programme workstreams", decision: "Leadership decision", inputs: "Inputs", deliverable: "Deliverable", human: "Human responsibility", note: tr(programmeNote, locale) } : { group: "計劃工作範疇", decision: "管理層決定", inputs: "輸入", deliverable: "成果", human: "人手責任", note: tr(programmeNote, locale) }}
    />
  );
}

export function EcosystemMapBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <EcosystemMap
      groups={memberGroups.map((g) => ({
        id: g.id,
        name: tr(g.name, locale),
        copy: tr(g.copy, locale),
        members: members
          .filter((m) => m.group === g.id)
          .map((m) => ({
            id: m.id,
            name: m.name,
            role: tr(m.role, locale),
            relationship: tr(m.relationship, locale),
            audience: tr(m.audience, locale),
            why: tr(m.why, locale),
            services: m.services.map((s) => ({ label: tr(serviceById(s).name, locale), href: href(locale, paths.service(s)) })),
            industries: m.industries.map((i) => ({ label: tr(industryById(i).name, locale), href: href(locale, paths.industry(i)) })),
            detail: { label: en ? `Explore ${m.name}` : `了解 ${m.name}`, href: href(locale, paths.member(m.id)) },
            external: m.externalUrl ? { label: tr(m.externalUrl.label, locale), href: m.externalUrl.url } : undefined,
          })),
      }))}
      labels={en ? { group: "Ecosystem members", audience: "Audience", relationship: "Relationship to FIMMICK", services: "Related services", industries: "Relevant industries", why: "Why it matters:", boundary: tr(ecosystemBoundary, locale) } : { group: "生態系統成員", audience: "受眾", relationship: "與 FIMMICK 的關係", services: "相關服務", industries: "相關行業", why: "重要之處：", boundary: tr(ecosystemBoundary, locale) }}
    />
  );
}

export function HeatmapTable({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <div className="table-wrap">
      <table className="data heatmap">
        <caption>{en ? "Illustrative sample. Ratings: 1 = not ready, 2 = needs preparation, 3 = ready. Not a validated maturity score." : "示例。評級：1＝未準備好，2＝需要準備，3＝已準備好。並非經驗證的成熟度分數。"}</caption>
        <thead>
          <tr>
            <th scope="col">{en ? "Workflow" : "流程"}</th>
            {heatmapColumns.map((c) => (
              <th scope="col" key={c.en}>
                {tr(c, locale)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sampleHeatmap.map((row) => (
            <tr key={row.area.en}>
              <th scope="row" style={{ background: "var(--surface)", textTransform: "none", letterSpacing: 0, color: "var(--ink)", fontSize: "var(--fs-small)" }}>
                {tr(row.area, locale)}
              </th>
              {row.ratings.map((r, i) => (
                <td key={i} className={`r r${r}`}>
                  {r}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ------------------------------------------------------------ card groups */

export function ProductCards({ locale, ids }: { locale: Locale; ids: ProductId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const p = productById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.product(id))}>
            <span className="card-meta">{tr(solutionById(p.solution).short, locale)}</span>
            <h3>{p.name}</h3>
            <p className="small muted">{tr(p.descriptor, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function ServiceCards({ locale, ids }: { locale: Locale; ids: ServiceId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const s = serviceById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.service(id))}>
            <span className="card-meta">{tr(s.eyebrow, locale)}</span>
            <h3>{tr(s.name, locale)}</h3>
            <p className="small muted">{tr(s.summary, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function IndustryCards({ locale, ids }: { locale: Locale; ids: IndustryId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const i = industryById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.industry(id))}>
            <h3>{tr(i.name, locale)}</h3>
            <p className="small muted">{tr(i.output, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function CaseCards({ locale, items }: { locale: Locale; items: CaseStudy[] }) {
  return (
    <div className="related-grid">
      {items.map((c) => (
        <Link key={c.slug} className="card card--link" href={href(locale, paths.case(c.slug))}>
          <span className="card-meta">
            <span className={c.kind === "client-work" ? "chip chip--sky" : "chip chip--lime"}>{tr(caseKindLabel[c.kind], locale)}</span>
            {tr(c.sector, locale)} · {tr(c.market, locale)}
          </span>
          <h3>{tr(c.title, locale)}</h3>
          <p className="small muted">{tr(c.problem, locale)}</p>
          <span className="card-foot">
            {locale === "en" ? "Read the case" : "閱讀案例"} <span aria-hidden="true">→</span>
          </span>
        </Link>
      ))}
    </div>
  );
}

export function RelatedSection({ title, children, tint }: { title: string; children: ReactNode; tint?: boolean }) {
  return (
    <section className={tint ? "section section--tight section--surface" : "section section--tight"}>
      <div className="container related-block">
        <h2>{title}</h2>
        {children}
      </div>
    </section>
  );
}

export function EnquirySection({ locale, title, body, primary, secondary }: { locale: Locale; title: string; body?: string; primary: { label: string; to: string }; secondary?: { label: string; to: string } }) {
  return (
    <section className="section section--tight">
      <div className="container">
        <CtaBand
          title={title}
          body={body}
          actions={
            <>
              <LinkButton to={href(locale, primary.to)} variant="accent">
                {primary.label}
              </LinkButton>
              {secondary ? (
                <LinkButton to={href(locale, secondary.to)} variant="light">
                  {secondary.label}
                </LinkButton>
              ) : null}
            </>
          }
        />
      </div>
    </section>
  );
}

export function workstreamCardsData(locale: Locale) {
  return ["ai-readiness-maturity", "strategy-roadmap", "workflow-agent-design", "governance-adoption"].map((id) => workstreamById(id as never)).map((w) => ({ id: w.id, name: tr(w.name, locale), q: tr(w.leadershipQuestion, locale), artifact: tr(w.artifactLabel, locale), href: href(locale, paths.workstream(w.id)), code: w.code }));
}

export const allServices = services;
