import Link from "next/link";
import type { ReactNode } from "react";
import { href, t, type L, type Locale, zh } from "@/lib/i18n";
import { paths } from "@/lib/routes";
import { ui } from "@/content/ui";
import { products, productById } from "@/content/products";
import { services, serviceById } from "@/content/services";
import { industries, industryById } from "@/content/industries";
import { cases, caseKindLabel } from "@/content/cases";
import { members, memberGroups, ecosystemBoundary } from "@/content/ecosystem";
import { platformLayers, sampleScenario } from "@/content/platform";
import { programme, programmeNote, sampleHeatmap, heatmapColumns, workstreamById } from "@/content/transformation";
import { solutionById } from "@/content/solutions";
import { functionById, type FunctionId } from "@/content/functions";
import * as ex from "@/content/examples";
import type { CaseStudy, ExampleId, IndustryId, ProductId, ServiceId, SolutionId } from "@/content/types";
import { PlatformLayers } from "./diagrams/PlatformLayers";
import { BeforeAfter, type BaStep } from "./diagrams/BeforeAfter";
import { IndustryMap, type IndustryView } from "./diagrams/IndustryMap";
import { Roadmap } from "./diagrams/Roadmap";
import { EcosystemMap } from "./diagrams/EcosystemMap";
import { ExampleViewer, SingleExample, type ExampleBundle } from "./examples/ExampleViewer";
import type { ExampleChrome } from "./examples/Examples";
import { CtaBand, LinkButton } from "./ui";

const tr = <T,>(value: L<T>, locale: Locale) => t(value, locale);

/* ---------------------------------------------------------------- examples */

function chrome(locale: Locale, id: ExampleId, productId: ProductId, contactLabel?: L): ExampleChrome {
  const meta = ex.exampleMeta[id];
  const en = locale === "en";
  return {
    title: tr(meta.title, locale),
    lead: tr(meta.lead, locale),
    notice: tr(ex.sampleNotice, locale),
    reset: tr(ui.reset, locale),
    panes: en ? { input: "Input", work: "Prepared work", review: "Human review", output: "Output" } : { input: zh("輸入", locale), work: zh("準備好的工作", locale), review: zh("人手審閱", locale), output: zh("輸出", locale) },
    footnote: en
      ? "Runs entirely in your browser with fixed sample data. Nothing is sent, published, synced or generated by AI in this example."
      : zh("此示例只在你的瀏覽器內以固定示例資料運行，不會發送、發布、同步任何內容，亦不涉及實際 AI 生成。", locale),
    productCta: { label: zh(`${en ? "See" : "了解"} ${productById(productId).name}`, locale), href: href(locale, paths.product(productId)) },
    contactCta: { label: tr(contactLabel ?? ui.discussConfiguration, locale), href: href(locale, paths.contact({ intent: "configuration", product: productId, example: id })) },
  };
}

export function exampleData<K extends ExampleId>(locale: Locale, id: K): ExampleBundle[K] {
  const en = locale === "en";
  const toneLabel = (tone: string) => (en ? { positive: "Positive", negative: "Negative", mixed: "Mixed / question" } : { positive: zh("正面", locale), negative: zh("負面", locale), mixed: zh("中性／提問", locale) })[tone as "positive"] ?? tone;
  const builders: { [P in ExampleId]: () => ExampleBundle[P] } = {
    intelligence: () => ({
      chrome: chrome(locale, "intelligence", "social-listening"),
      topics: ex.intelTopics.map((x) => ({ id: x.id, label: tr(x.label, locale) })),
      sources: ex.intelSources.map((x) => ({ id: x.id, label: tr(x.label, locale) })),
      evidence: ex.intelEvidence.map((e) => ({ ...e, text: tr(e.text, locale), toneLabel: toneLabel(e.tone) })),
      interpretation: Object.fromEntries(Object.entries(ex.intelInterpretation).map(([k, v]) => [k, { summary: tr(v.summary, locale), priorities: v.priorities.map((p) => tr(p, locale)) }])),
      aiso: ex.aisoChecks.map((c) => ({ ...c, question: tr(c.question, locale), note: tr(c.note, locale) })),
      s: en
        ? { topic: "Topic", dataset: "Dataset", listening: "Social listening", aiSearch: "AI-search check (AISO)", source: "Source category", allSources: "All sources", evidence: "Linked evidence", none: "No sample evidence for this source.", interpretation: "Draft interpretation", priorities: "Prioritised actions", analyst: "Analyst review", markReviewed: "Mark priorities reviewed", reviewed: "Reviewed by analyst (sample)", notReviewed: "Awaiting analyst review", mentioned: "Brand mentioned", notMentioned: "Brand not mentioned", separate: "Listening and AI-search evidence are separate datasets and are never combined into one score." }
        : { topic: zh("話題", locale), dataset: zh("資料組合", locale), listening: zh("社交聆聽", locale), aiSearch: zh("AI 搜尋檢查（AISO）", locale), source: zh("來源類別", locale), allSources: zh("全部來源", locale), evidence: zh("已連結證據", locale), none: zh("此來源沒有示例證據。", locale), interpretation: zh("解讀草稿", locale), priorities: zh("優先行動", locale), analyst: zh("分析師審閱", locale), markReviewed: zh("標記優先次序已審閱", locale), reviewed: zh("分析師已審閱（示例）", locale), notReviewed: zh("等待分析師審閱", locale), mentioned: zh("有提及品牌", locale), notMentioned: zh("未有提及品牌", locale), separate: zh("社交聆聽與 AI 搜尋證據屬不同資料組合，不會合併成單一分數。", locale) },
    }),
    content: () => ({
      chrome: chrome(locale, "content", "creativemax"),
      facts: tr(ex.contentFacts, locale),
      scenarios: ex.contentScenarios.map((s) => ({ id: s.id, label: tr(s.label, locale), extraFacts: tr(s.extraFacts, locale), formats: s.formats.map((f) => ({ id: f.id, label: tr(f.label, locale), draft: tr(f.draft, locale) })) })),
      s: en
        ? { scenario: "Scenario", format: "Format", facts: "Approved source facts", draft: "Editable draft", editHint: "Edit freely. Editing a reviewed draft sends it back for review.", markReviewed: "Mark sample reviewed", statusDraft: "Draft — not reviewed", statusReviewed: "Reviewed (sample)", statusChanged: "Changed since review — review again", priceCheckOk: "No price mentioned (none supplied)", priceCheckWarn: "Mentions a price — not in the approved facts", factsLinked: "Draft uses only the listed facts", exportLabel: "Export sample file", exportDisabled: "Export is available once the current draft is reviewed.", exported: "Sample file downloaded (.txt).", fileHeader: "ILLUSTRATIVE SAMPLE — FIMMICK content workflow example. Sample data only; not a real campaign or approval.", reviewer: "Reviewer: Brand manager (sample role)" }
        : { scenario: zh("情境", locale), format: zh("格式", locale), facts: zh("已確認來源資料", locale), draft: zh("可編輯草稿", locale), editHint: zh("可自由修改；已審閱的草稿一經修改，便需重新審閱。", locale), markReviewed: zh("標記示例為已審閱", locale), statusDraft: zh("草稿——未審閱", locale), statusReviewed: zh("已審閱（示例）", locale), statusChanged: zh("審閱後曾修改——請重新審閱", locale), priceCheckOk: zh("沒有提及價錢（未有提供）", locale), priceCheckWarn: zh("提及價錢——不在已確認資料之內", locale), factsLinked: zh("草稿只使用所列資料", locale), exportLabel: zh("匯出示例檔案", locale), exportDisabled: zh("目前草稿審閱後即可匯出。", locale), exported: zh("已下載示例檔案（.txt）。", locale), fileHeader: zh("示例檔案 —— FIMMICK 內容流程示範，只含示例資料，並非真實宣傳或批核。", locale), reviewer: zh("審閱人：品牌經理（示例角色）", locale) },
    }),
    "follow-up": () => ({
      chrome: chrome(locale, "follow-up", "customer-ops"),
      enquiries: ex.enquiries.map((e) => ({ ...e, channel: tr(e.channel, locale), message: tr(e.message, locale), intent: tr(e.intent, locale), priority: tr(e.priority, locale), drafts: Object.fromEntries(Object.entries(e.drafts).map(([k, v]) => [k, v ? tr(v, locale) : null])) })),
      owners: ex.owners.map((o) => ({ id: o.id, label: tr(o.label, locale) })),
      actions: ex.nextActions.map((a) => ({ id: a.id, label: tr(a.label, locale) })),
      s: en
        ? { enquiry: "Sample enquiry", record: "Record", channel: "Channel", received: "Received", intent: "Intent", priority: "Priority", owner: "Owner", action: "Next action", suggested: "suggested", draft: "Proposed response", noDraft: "No draft — this category goes straight to a person.", humanOnly: "Human-only category", approve: "Owner approves task", statusOpen: "Open — awaiting owner", statusApproved: "Approved by owner (sample)", notSent: "Nothing is sent in this example. Sending needs a configured channel and your approval rules.", task: "Next task", due: "Follow-up by" }
        : { enquiry: zh("示例查詢", locale), record: zh("紀錄", locale), channel: zh("渠道", locale), received: zh("收到時間", locale), intent: zh("意圖", locale), priority: zh("優先次序", locale), owner: zh("負責人", locale), action: zh("下一步行動", locale), suggested: zh("建議", locale), draft: zh("建議回覆", locale), noDraft: zh("不設草稿——此類別直接交由專人處理。", locale), humanOnly: zh("只限專人處理", locale), approve: zh("負責人批准工作", locale), statusOpen: zh("待處理——等待負責人", locale), statusApproved: zh("負責人已批准（示例）", locale), notSent: zh("此示例不會發送任何內容；發送需要已設定的渠道及你的批核規則。", locale), task: zh("下一步工作", locale), due: zh("跟進期限", locale) },
    }),
    "website-ops": () => ({
      chrome: chrome(locale, "website-ops", "website-cms"),
      changes: ex.recordChanges.map((c) => ({ id: c.id, label: tr(c.label, locale), record: c.record, variant: c.id === "new-colour" ? "stone" : c.id === "missing-field" ? "lime" : "blue", fields: c.fields.map((f) => ({ name: tr(f.name, locale), before: tr(f.before, locale), after: tr(f.after, locale), changed: f.changed, valid: f.valid, note: f.note ? tr(f.note, locale) : undefined })), preview: { title: tr(c.preview.title, locale), lines: c.preview.lines.map((l) => tr(l, locale)) } })),
      s: en
        ? { change: "Record change", record: "Record", field: "Field", before: "Before", after: "After", validation: "Validation", valid: "all required fields present", invalid: "required field missing — held", approve: "Approve change", returnLabel: "Return", statusPending: "Awaiting review", statusApproved: "Approved — preview updated (sample)", statusReturned: "Returned to editor", statusHeld: "Held until the missing field is supplied", preview: "Page preview · sample", previewNote: "Preview only. Nothing is published in this example.", history: "Change history", historyCreated: "change drafted from record", historyApproved: "approved by content owner (sample)", historyReturned: "returned by content owner (sample)" }
        : { change: zh("紀錄變更", locale), record: zh("紀錄", locale), field: zh("欄位", locale), before: zh("更新前", locale), after: zh("更新後", locale), validation: zh("驗證", locale), valid: zh("必填欄位齊全", locale), invalid: zh("欠缺必填欄位——暫緩", locale), approve: zh("批准變更", locale), returnLabel: zh("退回", locale), statusPending: zh("等待審閱", locale), statusApproved: zh("已批准——預覽已更新（示例）", locale), statusReturned: zh("已退回編輯", locale), statusHeld: zh("補交缺漏欄位前暫緩", locale), preview: zh("頁面預覽·示例", locale), previewNote: zh("只供預覽，此示例不會發布任何內容。", locale), history: zh("變更紀錄", locale), historyCreated: zh("根據紀錄草擬變更", locale), historyApproved: zh("內容負責人已批准（示例）", locale), historyReturned: zh("內容負責人已退回（示例）", locale) },
    }),
  };
  return builders[id]() as ExampleBundle[K];
}

export function ExampleTabs({ locale, initial = "content" }: { locale: Locale; initial?: ExampleId }) {
  const bundle: ExampleBundle = {
    intelligence: exampleData(locale, "intelligence"),
    content: exampleData(locale, "content"),
    "follow-up": exampleData(locale, "follow-up"),
    "website-ops": exampleData(locale, "website-ops"),
  };
  const tabs = (["intelligence", "content", "follow-up", "website-ops"] as const).map((id) => ({
    id,
    label: tr(solutionById(ex.exampleMeta[id].solution).short, locale),
    hint: ex.exampleMeta[id].products.map((p) => productById(p).name).join(" · "),
  }));
  return <ExampleViewer bundle={bundle} tabs={tabs} initial={initial} label={locale === "en" ? "Choose an example" : zh("選擇示例", locale)} />;
}

export function ExampleBlock({ locale, id }: { locale: Locale; id: ExampleId }) {
  switch (id) {
    case "intelligence":
      return <SingleExample id="intelligence" data={exampleData(locale, "intelligence")} />;
    case "content":
      return <SingleExample id="content" data={exampleData(locale, "content")} />;
    case "follow-up":
      return <SingleExample id="follow-up" data={exampleData(locale, "follow-up")} />;
    default:
      return <SingleExample id="website-ops" data={exampleData(locale, "website-ops")} />;
  }
}

/* ---------------------------------------------------------------- diagrams */

export function PlatformLayersBlock({ locale, variant = "dark" }: { locale: Locale; variant?: "dark" | "light" }) {
  const en = locale === "en";
  return (
    <PlatformLayers
      variant={variant}
      layers={platformLayers.map((l) => ({ id: l.id, number: l.number, name: tr(l.name, locale), question: tr(l.question, locale), explanation: tr(l.explanation, locale), shows: tr(l.shows, locale), scenarioLabel: tr(l.scenario.label, locale), scenarioItems: tr(l.scenario.items, locale) }))}
      steps={sampleScenario.steps.map((s) => tr(s, locale))}
      labels={en ? { shows: "What this layer shows", scenario: "In the sample", select: "Platform layers", journey: "Sample scenario steps" } : { shows: zh("此層展示", locale), scenario: zh("示例中", locale), select: zh("平台層", locale), journey: zh("示例情境步驟", locale) }}
    />
  );
}

export function BeforeAfterBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  const before: BaStep[] = en
    ? [
        { title: "Brief arrives by email", copy: "Facts sit in an attachment and a chat thread.", kind: "manual", tag: "Manual" },
        { title: "Copy written from memory", copy: "Claims are retyped; colour names drift.", kind: "pain", tag: "Risk" },
        { title: "Approval in chat", copy: "“Looks good” in a group chat; no record of what was approved.", kind: "pain", tag: "Risk" },
        { title: "Re-edits after approval", copy: "Changes made after sign-off go unnoticed.", kind: "pain", tag: "Risk" },
        { title: "Files emailed around", copy: "Final version unclear; nothing reusable next time.", kind: "manual", tag: "Manual" },
      ]
    : [
        { title: zh("以電郵收到簡報", locale), copy: zh("資料散落在附件及聊天記錄中。", locale), kind: "manual", tag: zh("人手", locale) },
        { title: zh("憑記憶撰寫文案", locale), copy: zh("宣稱重新打字；顏色名稱出錯。", locale), kind: "pain", tag: zh("風險", locale) },
        { title: zh("在聊天中批核", locale), copy: zh("群組中一句「好」，卻沒有記錄批准了甚麼。", locale), kind: "pain", tag: zh("風險", locale) },
        { title: zh("批准後再修改", locale), copy: zh("確認後的改動無人察覺。", locale), kind: "pain", tag: zh("風險", locale) },
        { title: zh("以電郵傳送檔案", locale), copy: zh("最終版本不清，下次無法重用。", locale), kind: "manual", tag: zh("人手", locale) },
      ];
  const after: BaStep[] = en
    ? [
        { title: "Approved facts as the source", copy: "The brief links to one list of approved facts.", kind: "system", tag: "Data" },
        { title: "Drafts prepared from the facts", copy: "Variants show which facts they used.", kind: "ai", tag: "AI prepares" },
        { title: "Named reviewer decides", copy: "Approve, edit or return — each decision is recorded.", kind: "human", tag: "People decide" },
        { title: "Edits reset approval", copy: "Changing an approved draft sends it back for review.", kind: "human", tag: "Control" },
        { title: "Export with record", copy: "Selected items leave with sources and review notes.", kind: "system", tag: "Record" },
      ]
    : [
        { title: zh("以已確認資料作來源", locale), copy: zh("簡報連結到一份已確認資料清單。", locale), kind: "system", tag: zh("資料", locale) },
        { title: zh("根據資料準備草稿", locale), copy: zh("每個版本都列明所用資料。", locale), kind: "ai", tag: zh("AI 準備", locale) },
        { title: zh("由指定審閱人決定", locale), copy: zh("批准、修改或退回，每個決定都有記錄。", locale), kind: "human", tag: zh("由人決定", locale) },
        { title: zh("修改即需重新批核", locale), copy: zh("已批准的草稿一經修改便退回審閱。", locale), kind: "human", tag: zh("管控", locale) },
        { title: zh("連記錄一併匯出", locale), copy: zh("選定內容連同來源及審閱意見輸出。", locale), kind: "system", tag: zh("記錄", locale) },
      ];
  return (
    <BeforeAfter
      before={before}
      after={after}
      labels={en ? { before: "Before: manual handoffs", after: "After: reviewed workflow", group: "Compare workflows", note: "Process comparison only. No time or cost savings are claimed; results depend on your workflow and are measured after a first deployment." } : { before: zh("之前：人手交接", locale), after: zh("之後：經審閱的流程", locale), group: zh("比較流程", locale), note: zh("此為流程比較，並不聲稱節省任何時間或成本；實際成效視乎你的流程，並於首次部署後量度。", locale) }}
    />
  );
}

export function IndustryMapBlock({ locale, ids }: { locale: Locale; ids?: IndustryId[] }) {
  const en = locale === "en";
  const list = ids ? ids.map(industryById) : industries;
  const views: IndustryView[] = list.map((i) => {
    const evidenceCase = cases.find((c) => c.industries.includes(i.id) && c.kind === "client-work");
    return {
      id: i.id,
      name: tr(i.name, locale),
      short: i.products.map((p) => productById(p).name).join(" · "),
      problem: tr(i.problem, locale),
      journey: i.journey.map((j) => ({ step: tr(j.step, locale), copy: tr(j.copy, locale), human: !!j.human, who: j.human ? (en ? "Your team decides" : zh("由你的團隊決定", locale)) : j.product ? productById(j.product).name : "" })),
      products: i.products.map((p) => ({ label: productById(p).name, href: href(locale, paths.product(p)) })),
      services: i.services.map((s) => ({ label: tr(serviceById(s).name, locale), href: href(locale, paths.service(s)) })),
      evidence: evidenceCase ? { label: tr(evidenceCase.title, locale), href: href(locale, paths.case(evidenceCase.slug)), kind: tr(caseKindLabel[evidenceCase.kind], locale) } : undefined,
      proof: tr(i.proof, locale),
      output: tr(i.output, locale),
      cta: { label: en ? `Discuss ${tr(i.name, locale)}` : zh(`討論${tr(i.name, locale)}方案`, locale), href: href(locale, paths.contact({ intent: "configuration", industry: i.id })) },
      detail: { label: en ? "Full industry page" : zh("查看完整行業頁面", locale), href: href(locale, paths.industry(i.id)) },
    };
  });
  return <IndustryMap industries={views} labels={en ? { group: "Choose a sector", products: "Products", services: "Services", evidence: "Evidence", output: "Output", noEvidence: "No published case for this sector yet — the workflow shown is a labelled example." } : { group: zh("選擇行業", locale), products: zh("產品", locale), services: zh("服務", locale), evidence: zh("證據", locale), output: zh("成果", locale), noEvidence: zh("此行業暫未有公開案例——所示流程為已標示的示例。", locale) }} />;
}

export function IndustryMatrix({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <div className="table-wrap">
      <table className="data matrix">
        <caption className="sr-only">{en ? "Which products each industry page applies" : zh("各行業應用的產品", locale)}</caption>
        <thead>
          <tr>
            <th scope="col">{en ? "Industry" : zh("行業", locale)}</th>
            {products.map((p) => (
              <th scope="col" key={p.id}>
                {p.name}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {industries.map((i) => (
            <tr key={i.id}>
              <th scope="row">
                <Link href={href(locale, paths.industry(i.id))}>{tr(i.name, locale)}</Link>
              </th>
              {products.map((p) =>
                i.products.includes(p.id) ? (
                  <td key={p.id} className="on">
                    <span aria-hidden="true" />
                    <span className="sr-only">{en ? "Applied" : zh("適用", locale)}</span>
                  </td>
                ) : (
                  <td key={p.id} className="off" aria-label={en ? "Not applied" : zh("不適用", locale)}>
                    –
                  </td>
                ),
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function RoadmapBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <Roadmap
      steps={programme.map((p) => ({
        id: p.id,
        number: p.number,
        name: tr(p.name, locale),
        decision: tr(p.decision, locale),
        inputs: tr(p.inputs, locale),
        deliverable: tr(p.deliverable, locale),
        humanRole: tr(p.humanRole, locale),
        link: p.workstream
          ? { label: tr(workstreamById(p.workstream).name, locale), href: href(locale, paths.workstream(p.workstream)) }
          : p.service
            ? { label: tr(serviceById(p.service).name, locale), href: href(locale, paths.service(p.service)) }
            : undefined,
      }))}
      labels={en ? { group: "Programme workstreams", decision: "Leadership decision", inputs: "Inputs", deliverable: "Deliverable", human: "Human responsibility", note: tr(programmeNote, locale) } : { group: zh("計劃工作範疇", locale), decision: zh("管理層決定", locale), inputs: zh("輸入", locale), deliverable: zh("成果", locale), human: zh("人手責任", locale), note: tr(programmeNote, locale) }}
    />
  );
}

export function EcosystemMapBlock({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <EcosystemMap
      groups={memberGroups.map((g) => ({
        id: g.id,
        name: tr(g.name, locale),
        copy: tr(g.copy, locale),
        members: members
          .filter((m) => m.group === g.id)
          .map((m) => ({
            id: m.id,
            name: m.name,
            role: tr(m.role, locale),
            relationship: tr(m.relationship, locale),
            audience: tr(m.audience, locale),
            why: tr(m.why, locale),
            services: m.services.map((s) => ({ label: tr(serviceById(s).name, locale), href: href(locale, paths.service(s)) })),
            industries: m.industries.map((i) => ({ label: tr(industryById(i).name, locale), href: href(locale, paths.industry(i)) })),
            detail: { label: en ? `Explore ${m.name}` : zh(`了解 ${m.name}`, locale), href: href(locale, paths.member(m.id)) },
            external: m.externalUrl ? { label: tr(m.externalUrl.label, locale), href: m.externalUrl.url } : undefined,
          })),
      }))}
      labels={en ? { group: "Ecosystem members", audience: "Audience", relationship: "Relationship to FIMMICK", services: "Related services", industries: "Relevant industries", why: "Why it matters:", boundary: tr(ecosystemBoundary, locale) } : { group: zh("生態系統成員", locale), audience: zh("受眾", locale), relationship: zh("與 FIMMICK 的關係", locale), services: zh("相關服務", locale), industries: zh("相關行業", locale), why: zh("重要之處：", locale), boundary: tr(ecosystemBoundary, locale) }}
    />
  );
}

export function HeatmapTable({ locale }: { locale: Locale }) {
  const en = locale === "en";
  return (
    <div className="table-wrap">
      <table className="data heatmap">
        <caption>{en ? "Illustrative sample. Ratings: 1 = not ready, 2 = needs preparation, 3 = ready. Not a validated maturity score." : zh("示例。評級：1＝未準備好，2＝需要準備，3＝已準備好。並非經驗證的成熟度分數。", locale)}</caption>
        <thead>
          <tr>
            <th scope="col">{en ? "Workflow" : zh("流程", locale)}</th>
            {heatmapColumns.map((c) => (
              <th scope="col" key={c.en}>
                {tr(c, locale)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sampleHeatmap.map((row) => (
            <tr key={row.area.en}>
              <th scope="row" style={{ background: "var(--surface)", textTransform: "none", letterSpacing: 0, color: "var(--ink)", fontSize: "var(--fs-small)" }}>
                {tr(row.area, locale)}
              </th>
              {row.ratings.map((r, i) => (
                <td key={i} className={`r r${r}`}>
                  {r}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ------------------------------------------------------------ card groups */

export function ProductCards({ locale, ids }: { locale: Locale; ids: ProductId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const p = productById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.product(id))}>
            <span className="card-meta">{tr(solutionById(p.solution).short, locale)}</span>
            <h3>{p.name}</h3>
            <p className="small muted">{tr(p.descriptor, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function ServiceCards({ locale, ids }: { locale: Locale; ids: ServiceId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const s = serviceById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.service(id))}>
            <span className="card-meta">{tr(s.eyebrow, locale)}</span>
            <h3>{tr(s.name, locale)}</h3>
            <p className="small muted">{tr(s.summary, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function IndustryCards({ locale, ids }: { locale: Locale; ids: IndustryId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const i = industryById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.industry(id))}>
            <h3>{tr(i.name, locale)}</h3>
            <p className="small muted">{tr(i.output, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function SolutionCards({ locale, ids }: { locale: Locale; ids: SolutionId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const s = solutionById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.solution(id))}>
            <span className="card-meta">{s.products.map((p) => productById(p).name).join(" · ")}</span>
            <h3>{tr(s.name, locale)}</h3>
            <p className="small muted">{tr(s.job, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

export function FunctionCards({ locale, ids }: { locale: Locale; ids: FunctionId[] }) {
  return (
    <div className="related-grid">
      {ids.map((id) => {
        const f = functionById(id);
        return (
          <Link key={id} className="card card--link" href={href(locale, paths.function(id))}>
            <span className="card-meta">{tr(f.owner, locale)}</span>
            <h3>{tr(f.name, locale)}</h3>
            <p className="small muted">{tr(f.summary, locale)}</p>
            <span className="card-foot">
              {tr(ui.learnMore, locale)} <span aria-hidden="true">→</span>
            </span>
          </Link>
        );
      })}
    </div>
  );
}

/** Two-column sample record (label → value), marked as illustrative. */
export function SampleRecord({ locale, label, rows, id }: { locale: Locale; label: L; rows: L<[string, string][]>; id?: string }) {
  const en = locale === "en";
  return (
    <section className="section" id={id}>
      <div className="container split">
        <div className="stack">
          <p className="eyebrow">{en ? "Sample output" : zh("成果示例", locale)}</p>
          <h2>{tr(label, locale)}</h2>
          <p className="muted small">{en ? "Illustrative sample — not client data." : zh("示例——並非客戶資料。", locale)}</p>
        </div>
        <dl className="kv">
          {tr(rows, locale).map(([k, v]) => (
            <div key={k} style={{ display: "contents" }}>
              <dt>{k}</dt>
              <dd>{v}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}

/** `heading` is h2 where the cards sit directly under the page h1 (the case-studies hub). */
export function CaseCards({ locale, items, heading: Heading = "h3" }: { locale: Locale; items: CaseStudy[]; heading?: "h2" | "h3" }) {
  return (
    <div className="related-grid">
      {items.map((c) => (
        <Link key={c.slug} className="card card--link" href={href(locale, paths.case(c.slug))}>
          <span className="card-meta">
            <span className={c.kind === "client-work" ? "chip chip--sky" : "chip chip--lime"}>{tr(caseKindLabel[c.kind], locale)}</span>
            {tr(c.sector, locale)} · {tr(c.market, locale)}
          </span>
          <Heading>{tr(c.title, locale)}</Heading>
          <p className="small muted">{tr(c.problem, locale)}</p>
          <span className="card-foot">
            {locale === "en" ? "Read the case" : zh("閱讀案例", locale)} <span aria-hidden="true">→</span>
          </span>
        </Link>
      ))}
    </div>
  );
}

export function RelatedSection({ title, children, tint }: { title: string; children: ReactNode; tint?: boolean }) {
  return (
    <section className={tint ? "section section--tight section--surface" : "section section--tight"}>
      <div className="container related-block">
        <h2>{title}</h2>
        {children}
      </div>
    </section>
  );
}

export function EnquirySection({ locale, title, body, primary, secondary }: { locale: Locale; title: string; body?: string; primary: { label: string; to: string }; secondary?: { label: string; to: string } }) {
  return (
    <section className="section section--tight">
      <div className="container">
        <CtaBand
          title={title}
          body={body}
          actions={
            <>
              <LinkButton to={href(locale, primary.to)} variant="accent">
                {primary.label}
              </LinkButton>
              {secondary ? (
                <LinkButton to={href(locale, secondary.to)} variant="light">
                  {secondary.label}
                </LinkButton>
              ) : null}
            </>
          }
        />
      </div>
    </section>
  );
}

export function workstreamCardsData(locale: Locale) {
  return ["ai-readiness-maturity", "strategy-roadmap", "workflow-agent-design", "governance-adoption"].map((id) => workstreamById(id as never)).map((w) => ({ id: w.id, name: tr(w.name, locale), q: tr(w.leadershipQuestion, locale), artifact: tr(w.artifactLabel, locale), href: href(locale, paths.workstream(w.id)), code: w.code }));
}

export const allServices = services;

/** Four-step workflow strip using the flow-motif roles. The step marked `review` is where people decide. */
export function FlowStrip({ locale, steps, humanIndex = 2 }: { locale: Locale; steps: { title: L; copy: L }[]; humanIndex?: number }) {
  const en = locale === "en";
  const roleFor = (i: number) => (i === humanIndex ? "review" : i === 0 ? "source" : i === steps.length - 1 ? "result" : "work");
  const roleLabel: Record<string, string> = en
    ? { source: "Input", work: "AI prepares", review: "People decide", result: "Output" }
    : { source: zh("輸入", locale), work: zh("AI 準備", locale), review: zh("由人決定", locale), result: zh("輸出", locale) };
  return (
    <ol className="flow-strip">
      {steps.map((s, i) => (
        <li key={i} data-role={roleFor(i)}>
          <span className="role">
            {String(i + 1).padStart(2, "0")} · {roleLabel[roleFor(i)]}
          </span>
          <h3>{tr(s.title, locale)}</h3>
          <p>{tr(s.copy, locale)}</p>
        </li>
      ))}
    </ol>
  );
}

export function StatusPanel({ locale, availability, mode, extra }: { locale: Locale; availability: "available" | "configured" | "discuss"; mode: "illustrative-sample" | "recorded-demonstration" | "live-product"; extra?: { label: string; value: string }[] }) {
  const a = availability === "available" ? ui.availabilityAvailable : availability === "configured" ? ui.availabilityConfigured : ui.availabilityDiscuss;
  const m = mode === "illustrative-sample" ? ui.modeSample : mode === "recorded-demonstration" ? ui.modeRecorded : ui.modeLive;
  return (
    <dl className="status-panel">
      <div>
        <dt>{tr(ui.availability, locale)}</dt>
        <dd>{tr(a, locale)}</dd>
      </div>
      <div>
        <dt>{tr(ui.exampleMode, locale)}</dt>
        <dd>{tr(m, locale)}</dd>
      </div>
      {extra?.map((e) => (
        <div key={e.label}>
          <dt>{e.label}</dt>
          <dd>{e.value}</dd>
        </div>
      ))}
    </dl>
  );
}
